{
  "formatVersion": "1.1",
  "component": {
    "url": "../../waltid-mdoc-credentials2/1.0.0-SNAPSHOT/waltid-mdoc-credentials2-1.0.0-SNAPSHOT.module",
    "group": "id.walt.credentials",
    "module": "waltid-mdoc-credentials2",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "id.walt.crypto",
          "module": "waltid-cose",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "waltid-mdoc-credentials2-js-1.0.0-SNAPSHOT.klib",
          "url": "waltid-mdoc-credentials2-js-1.0.0-SNAPSHOT.klib",
          "size": 405214,
          "sha512": "1f8b1726b2016c3180c8a3675f6fc32a554a014159c7d9fc017615ebe961b681090bd4adc177a361afb36b2d15f5e21b686b5864e81b1f63fe095f97acde7dfa",
          "sha256": "444f77a5c6cf980cf820bd7fa0ec5d693b6299b884a2498e65b1464efafb5879",
          "sha1": "d5a8f0e7d9b71e0e73a89d91bc61e2eeaa4bfc55",
          "md5": "633a820fa9444e9b77efc09d9d744f8a"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "id.walt.crypto",
          "module": "waltid-cose",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.13"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "app.softwork",
          "module": "kotlinx-uuid-core",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.eygraber",
          "module": "jsonpathkt-kotlinx",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-cbor",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "net.orandja.obor",
          "module": "obor",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "org.kotlincrypto.random",
          "module": "crypto-rand",
          "version": {
            "requires": "0.5.2"
          }
        },
        {
          "group": "org.kotlincrypto.hash",
          "module": "bom",
          "version": {
            "requires": "0.7.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.kotlincrypto.hash",
          "module": "sha2"
        },
        {
          "group": "org.kotlincrypto.macs",
          "module": "bom",
          "version": {
            "requires": "0.7.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.kotlincrypto.macs",
          "module": "hmac-sha2"
        },
        {
          "group": "id.walt.crypto",
          "module": "waltid-crypto",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "waltid-mdoc-credentials2-js-1.0.0-SNAPSHOT.klib",
          "url": "waltid-mdoc-credentials2-js-1.0.0-SNAPSHOT.klib",
          "size": 405214,
          "sha512": "1f8b1726b2016c3180c8a3675f6fc32a554a014159c7d9fc017615ebe961b681090bd4adc177a361afb36b2d15f5e21b686b5864e81b1f63fe095f97acde7dfa",
          "sha256": "444f77a5c6cf980cf820bd7fa0ec5d693b6299b884a2498e65b1464efafb5879",
          "sha1": "d5a8f0e7d9b71e0e73a89d91bc61e2eeaa4bfc55",
          "md5": "633a820fa9444e9b77efc09d9d744f8a"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "waltid-mdoc-credentials2-js-1.0.0-SNAPSHOT-sources.jar",
          "url": "waltid-mdoc-credentials2-js-1.0.0-SNAPSHOT-sources.jar",
          "size": 77240,
          "sha512": "4cccf927eed815738079cb51791412a6fcf174eedcb4a309fd6866049349b8f9bceb817dda4f4ea09b44c78a920e1e1ac987ac6dc5f375c8631b56f81d3192cf",
          "sha256": "dced2c6f359152bda3f18f7ad16560d8b37701a7bc3d83541627f58894983d93",
          "sha1": "114fdbb64f5ff7334658c3ebaa2124e935898b9d",
          "md5": "462bc629e45dd9e7cc082edb777cb0b7"
        }
      ]
    }
  ]
}
