{
  "formatVersion": "1.1",
  "component": {
    "url": "../../waltid-mdoc-credentials2/1.0.0-SNAPSHOT/waltid-mdoc-credentials2-1.0.0-SNAPSHOT.module",
    "group": "id.walt.credentials",
    "module": "waltid-mdoc-credentials2",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "id.walt.crypto",
          "module": "waltid-cose",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.13"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "app.softwork",
          "module": "kotlinx-uuid-core",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.eygraber",
          "module": "jsonpathkt-kotlinx",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-cbor",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "net.orandja.obor",
          "module": "obor",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "org.kotlincrypto.random",
          "module": "crypto-rand",
          "version": {
            "requires": "0.5.2"
          }
        },
        {
          "group": "org.kotlincrypto.hash",
          "module": "bom",
          "version": {
            "requires": "0.7.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.kotlincrypto.hash",
          "module": "sha2"
        },
        {
          "group": "org.kotlincrypto.macs",
          "module": "bom",
          "version": {
            "requires": "0.7.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.kotlincrypto.macs",
          "module": "hmac-sha2"
        },
        {
          "group": "id.walt.crypto",
          "module": "waltid-crypto",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "waltid-mdoc-credentials2-iosSimulatorArm64Main-1.0.0-SNAPSHOT.klib",
          "url": "waltid-mdoc-credentials2-iossimulatorarm64-1.0.0-SNAPSHOT.klib",
          "size": 425838,
          "sha512": "2dfbf2b4d99ee9a4e59e8188a260bb391c66a978b4324520df5b7a3afd17e80a264bed6ffa2cdf055731ccb9edf24ff32ca9754569baab846c1b1e0591f20c39",
          "sha256": "93fa8734b76573372a217f1e72fb782f91a4dfdae307cd86d6b64b0ca33b270c",
          "sha1": "07976652557f085b315a9ec9caa05ef320ee0594",
          "md5": "968a148809ef8cee3f8f475f4eeb90a2"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "waltid-mdoc-credentials2-iossimulatorarm64-1.0.0-SNAPSHOT-sources.jar",
          "url": "waltid-mdoc-credentials2-iossimulatorarm64-1.0.0-SNAPSHOT-sources.jar",
          "size": 76055,
          "sha512": "2d8ec12756911f06b39c30cf39bef063f8d28a4e6862cea9558d2173b72ae8af87014b3dc5ddddf4914b9585617372d81585aea937234620d905bfb4f19301ac",
          "sha256": "75604db9e1f1cf824d0e262b78b99138e9fa85f094ba3907fab433ef9d47fcff",
          "sha1": "2f2c06ee0d43fd204eecf4bf555c27b92f31349e",
          "md5": "3634f247d416d960b7bd353c346ba920"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "id.walt.crypto",
          "module": "waltid-cose",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.13"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "app.softwork",
          "module": "kotlinx-uuid-core",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.eygraber",
          "module": "jsonpathkt-kotlinx",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-cbor",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "net.orandja.obor",
          "module": "obor",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "org.kotlincrypto.random",
          "module": "crypto-rand",
          "version": {
            "requires": "0.5.2"
          }
        },
        {
          "group": "org.kotlincrypto.hash",
          "module": "bom",
          "version": {
            "requires": "0.7.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.kotlincrypto.hash",
          "module": "sha2"
        },
        {
          "group": "org.kotlincrypto.macs",
          "module": "bom",
          "version": {
            "requires": "0.7.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.kotlincrypto.macs",
          "module": "hmac-sha2"
        },
        {
          "group": "id.walt.crypto",
          "module": "waltid-crypto",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "waltid-mdoc-credentials2-iossimulatorarm64-1.0.0-SNAPSHOT-metadata.jar",
          "url": "waltid-mdoc-credentials2-iossimulatorarm64-1.0.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
