{
  "formatVersion": "1.1",
  "component": {
    "group": "id.walt.did",
    "module": "waltid-did",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "id.walt.crypto",
          "module": "waltid-crypto",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "love.forte.plugin.suspend-transform",
          "module": "suspend-transform-runtime",
          "version": {
            "requires": "2.2.20-0.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "app.softwork",
          "module": "kotlinx-uuid-core",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "net.thauvin.erik.urlencoder",
          "module": "urlencoder-lib",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.5"
          }
        },
        {
          "group": "love.forte.plugin.suspend-transform",
          "module": "suspend-transform-annotation",
          "version": {
            "requires": "2.2.20-0.13.1"
          }
        }
      ],
      "files": [
        {
          "name": "waltid-did-1.0.0-SNAPSHOT.jar",
          "url": "waltid-did-1.0.0-SNAPSHOT.jar",
          "size": 73109,
          "sha512": "b2277beacb61aa31c297164b92835b0f648568019d0e88200d8b5f1aa6aaf865341c2c558056cbd2476e1cb76bff0a06594729a799b8ec9506863b30748fd1af",
          "sha256": "911829a20b6a747ee51ca5c925781f1c2b60d7b675f8af93a19d0088f488f866",
          "sha1": "41336db2de8ecd7fdb47ee9c096aabb21d4b384a",
          "md5": "1da4f99802debb16ca8ed926f5d4a78c"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "waltid-did-1.0.0-SNAPSHOT-sources.jar",
          "url": "waltid-did-1.0.0-SNAPSHOT-sources.jar",
          "size": 63372,
          "sha512": "77e08928f5a25bda8d92c7a9fcc4f7325f5bba8427af1d78828b73798034bd6aba679852d0be893257117892a58dbf111092b59e09c2f674b6086ef3f0e02854",
          "sha256": "69875719b17bd78bcdf7cb66f957ed8a4e248b98584b3359d365f0ace923fb78",
          "sha1": "12fe1d4afdd0b0393f4d14ada714d6f786bec59f",
          "md5": "8029f9185a40760b7f39c9c2a2c0e792"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../waltid-did-iosarm64/1.0.0-SNAPSHOT/waltid-did-iosarm64-1.0.0-SNAPSHOT.module",
        "group": "id.walt.did",
        "module": "waltid-did-iosarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../waltid-did-iosarm64/1.0.0-SNAPSHOT/waltid-did-iosarm64-1.0.0-SNAPSHOT.module",
        "group": "id.walt.did",
        "module": "waltid-did-iosarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../waltid-did-iosarm64/1.0.0-SNAPSHOT/waltid-did-iosarm64-1.0.0-SNAPSHOT.module",
        "group": "id.walt.did",
        "module": "waltid-did-iosarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../waltid-did-iossimulatorarm64/1.0.0-SNAPSHOT/waltid-did-iossimulatorarm64-1.0.0-SNAPSHOT.module",
        "group": "id.walt.did",
        "module": "waltid-did-iossimulatorarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../waltid-did-iossimulatorarm64/1.0.0-SNAPSHOT/waltid-did-iossimulatorarm64-1.0.0-SNAPSHOT.module",
        "group": "id.walt.did",
        "module": "waltid-did-iossimulatorarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../waltid-did-iossimulatorarm64/1.0.0-SNAPSHOT/waltid-did-iossimulatorarm64-1.0.0-SNAPSHOT.module",
        "group": "id.walt.did",
        "module": "waltid-did-iossimulatorarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../waltid-did-js/1.0.0-SNAPSHOT/waltid-did-js-1.0.0-SNAPSHOT.module",
        "group": "id.walt.did",
        "module": "waltid-did-js",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../waltid-did-js/1.0.0-SNAPSHOT/waltid-did-js-1.0.0-SNAPSHOT.module",
        "group": "id.walt.did",
        "module": "waltid-did-js",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../waltid-did-js/1.0.0-SNAPSHOT/waltid-did-js-1.0.0-SNAPSHOT.module",
        "group": "id.walt.did",
        "module": "waltid-did-js",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../waltid-did-jvm/1.0.0-SNAPSHOT/waltid-did-jvm-1.0.0-SNAPSHOT.module",
        "group": "id.walt.did",
        "module": "waltid-did-jvm",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../waltid-did-jvm/1.0.0-SNAPSHOT/waltid-did-jvm-1.0.0-SNAPSHOT.module",
        "group": "id.walt.did",
        "module": "waltid-did-jvm",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../waltid-did-jvm/1.0.0-SNAPSHOT/waltid-did-jvm-1.0.0-SNAPSHOT.module",
        "group": "id.walt.did",
        "module": "waltid-did-jvm",
        "version": "1.0.0-SNAPSHOT"
      }
    }
  ]
}
