{
  "formatVersion": "1.1",
  "component": {
    "group": "id.walt.did",
    "module": "waltid-did",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "id.walt.crypto",
          "module": "waltid-crypto",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "love.forte.plugin.suspend-transform",
          "module": "suspend-transform-runtime",
          "version": {
            "requires": "2.2.20-0.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "app.softwork",
          "module": "kotlinx-uuid-core",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "net.thauvin.erik.urlencoder",
          "module": "urlencoder-lib",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.5"
          }
        },
        {
          "group": "love.forte.plugin.suspend-transform",
          "module": "suspend-transform-annotation",
          "version": {
            "requires": "2.2.20-0.13.1"
          }
        }
      ],
      "files": [
        {
          "name": "waltid-did-1.0.0-SNAPSHOT.jar",
          "url": "waltid-did-1.0.0-SNAPSHOT.jar",
          "size": 73112,
          "sha512": "2a2c09fd0de7728585782f480ed1a7c325d0453fbb68d792969d71f09a725a33ab5355df131c2f1828d7ba2d1a8d3530cdca2b61266570d484bd59338d4f4d8e",
          "sha256": "7b31f4adf998c15a4806612b454e5e90254379fdfe1b4bd3e620dfa456df47d7",
          "sha1": "232d477674433f3d7a6d453395d01ee19c7e1670",
          "md5": "91b9ffb5a9f05487988befa2e2940ab3"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "waltid-did-1.0.0-SNAPSHOT-sources.jar",
          "url": "waltid-did-1.0.0-SNAPSHOT-sources.jar",
          "size": 63368,
          "sha512": "3148e64ed40c5dd07efa787a92ba8ebe30cc92288cd863b5ec81127e34c5982245b49024fb3b20679e7f96475ba20ab41cca0222f43dc4d5cd2e2fcc6a3db491",
          "sha256": "a99b68edeafc424d20caf9b96688fa2e03729707c084d69e2a03691383daf3da",
          "sha1": "f323f2a79cae49667756883c00ac18a866b6df91",
          "md5": "fde3aa04f1d80162f60f9c61108d8cf6"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../waltid-did-iosarm64/1.0.0-SNAPSHOT/waltid-did-iosarm64-1.0.0-SNAPSHOT.module",
        "group": "id.walt.did",
        "module": "waltid-did-iosarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../waltid-did-iosarm64/1.0.0-SNAPSHOT/waltid-did-iosarm64-1.0.0-SNAPSHOT.module",
        "group": "id.walt.did",
        "module": "waltid-did-iosarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../waltid-did-iosarm64/1.0.0-SNAPSHOT/waltid-did-iosarm64-1.0.0-SNAPSHOT.module",
        "group": "id.walt.did",
        "module": "waltid-did-iosarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../waltid-did-iossimulatorarm64/1.0.0-SNAPSHOT/waltid-did-iossimulatorarm64-1.0.0-SNAPSHOT.module",
        "group": "id.walt.did",
        "module": "waltid-did-iossimulatorarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../waltid-did-iossimulatorarm64/1.0.0-SNAPSHOT/waltid-did-iossimulatorarm64-1.0.0-SNAPSHOT.module",
        "group": "id.walt.did",
        "module": "waltid-did-iossimulatorarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../waltid-did-iossimulatorarm64/1.0.0-SNAPSHOT/waltid-did-iossimulatorarm64-1.0.0-SNAPSHOT.module",
        "group": "id.walt.did",
        "module": "waltid-did-iossimulatorarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../waltid-did-js/1.0.0-SNAPSHOT/waltid-did-js-1.0.0-SNAPSHOT.module",
        "group": "id.walt.did",
        "module": "waltid-did-js",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../waltid-did-js/1.0.0-SNAPSHOT/waltid-did-js-1.0.0-SNAPSHOT.module",
        "group": "id.walt.did",
        "module": "waltid-did-js",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../waltid-did-js/1.0.0-SNAPSHOT/waltid-did-js-1.0.0-SNAPSHOT.module",
        "group": "id.walt.did",
        "module": "waltid-did-js",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../waltid-did-jvm/1.0.0-SNAPSHOT/waltid-did-jvm-1.0.0-SNAPSHOT.module",
        "group": "id.walt.did",
        "module": "waltid-did-jvm",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../waltid-did-jvm/1.0.0-SNAPSHOT/waltid-did-jvm-1.0.0-SNAPSHOT.module",
        "group": "id.walt.did",
        "module": "waltid-did-jvm",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../waltid-did-jvm/1.0.0-SNAPSHOT/waltid-did-jvm-1.0.0-SNAPSHOT.module",
        "group": "id.walt.did",
        "module": "waltid-did-jvm",
        "version": "1.0.0-SNAPSHOT"
      }
    }
  ]
}
