{
  "formatVersion": "1.1",
  "component": {
    "group": "id.walt.crypto",
    "module": "waltid-cose",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "id.walt.crypto",
          "module": "waltid-target-ios",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.5"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-cbor",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "id.walt.crypto",
          "module": "waltid-crypto",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.kotlincrypto.macs",
          "module": "bom",
          "version": {
            "requires": "0.7.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.kotlincrypto.macs",
          "module": "hmac-sha2"
        }
      ],
      "files": [
        {
          "name": "waltid-cose-1.0.0-SNAPSHOT.jar",
          "url": "waltid-cose-1.0.0-SNAPSHOT.jar",
          "size": 8900,
          "sha512": "863e24c39a843004221db8ad378ad8d7f647f1692505277cfeb45eba98f2a20fb0c888c178930e6a7659695c69a099171667d39784c0508c8541f9d393d6f949",
          "sha256": "4c9065831a139fad71990035095da49ba45dff2b4f1bee462a75de50c3ea5bac",
          "sha1": "5a0bd9f6ae55856d4404bc76318f955535c7a32d",
          "md5": "5b37e743407006eba6cd96a0c011a49c"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "waltid-cose-1.0.0-SNAPSHOT-sources.jar",
          "url": "waltid-cose-1.0.0-SNAPSHOT-sources.jar",
          "size": 11276,
          "sha512": "69fd8740da6dbd418095ddc8f67bdc315ff48bb75630561151613920ae4f5a9209e7a39af207351fd9ee0e6ed7122aa2f03dde4c5719fd10de0f9a6c9a7ed76b",
          "sha256": "1cf2f3de48cce77f7ea04a373873f43a6d9fe1aa325ca21d2732c7a45b87943c",
          "sha1": "8c7efc19dfc8969337b19e8228b1189f10c31d48",
          "md5": "ce5c42c4dce5b486b028e86aef5a7442"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../waltid-cose-iosarm64/1.0.0-SNAPSHOT/waltid-cose-iosarm64-1.0.0-SNAPSHOT.module",
        "group": "id.walt.crypto",
        "module": "waltid-cose-iosarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../waltid-cose-iosarm64/1.0.0-SNAPSHOT/waltid-cose-iosarm64-1.0.0-SNAPSHOT.module",
        "group": "id.walt.crypto",
        "module": "waltid-cose-iosarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../waltid-cose-iosarm64/1.0.0-SNAPSHOT/waltid-cose-iosarm64-1.0.0-SNAPSHOT.module",
        "group": "id.walt.crypto",
        "module": "waltid-cose-iosarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../waltid-cose-iossimulatorarm64/1.0.0-SNAPSHOT/waltid-cose-iossimulatorarm64-1.0.0-SNAPSHOT.module",
        "group": "id.walt.crypto",
        "module": "waltid-cose-iossimulatorarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../waltid-cose-iossimulatorarm64/1.0.0-SNAPSHOT/waltid-cose-iossimulatorarm64-1.0.0-SNAPSHOT.module",
        "group": "id.walt.crypto",
        "module": "waltid-cose-iossimulatorarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../waltid-cose-iossimulatorarm64/1.0.0-SNAPSHOT/waltid-cose-iossimulatorarm64-1.0.0-SNAPSHOT.module",
        "group": "id.walt.crypto",
        "module": "waltid-cose-iossimulatorarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../waltid-cose-js/1.0.0-SNAPSHOT/waltid-cose-js-1.0.0-SNAPSHOT.module",
        "group": "id.walt.crypto",
        "module": "waltid-cose-js",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../waltid-cose-js/1.0.0-SNAPSHOT/waltid-cose-js-1.0.0-SNAPSHOT.module",
        "group": "id.walt.crypto",
        "module": "waltid-cose-js",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../waltid-cose-js/1.0.0-SNAPSHOT/waltid-cose-js-1.0.0-SNAPSHOT.module",
        "group": "id.walt.crypto",
        "module": "waltid-cose-js",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../waltid-cose-jvm/1.0.0-SNAPSHOT/waltid-cose-jvm-1.0.0-SNAPSHOT.module",
        "group": "id.walt.crypto",
        "module": "waltid-cose-jvm",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../waltid-cose-jvm/1.0.0-SNAPSHOT/waltid-cose-jvm-1.0.0-SNAPSHOT.module",
        "group": "id.walt.crypto",
        "module": "waltid-cose-jvm",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../waltid-cose-jvm/1.0.0-SNAPSHOT/waltid-cose-jvm-1.0.0-SNAPSHOT.module",
        "group": "id.walt.crypto",
        "module": "waltid-cose-jvm",
        "version": "1.0.0-SNAPSHOT"
      }
    }
  ]
}
