{
  "formatVersion": "1.1",
  "component": {
    "url": "../../waltid-dif-definitions-parser/1.0.0-SNAPSHOT/waltid-dif-definitions-parser-1.0.0-SNAPSHOT.module",
    "group": "id.walt.dif-definitions-parser",
    "module": "waltid-dif-definitions-parser",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.eygraber",
          "module": "jsonpathkt-kotlinx",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.optimumcode",
          "module": "json-schema-validator",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "id.walt.credentials",
          "module": "waltid-w3c-credentials",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "waltid-dif-definitions-parser-iosSimulatorArm64Main-1.0.0-SNAPSHOT.klib",
          "url": "waltid-dif-definitions-parser-iossimulatorarm64-1.0.0-SNAPSHOT.klib",
          "size": 65201,
          "sha512": "8736d9a8fed21f835fa1ac6d18eb7c650f46d072be33ccd3190316b3e9a18e538220eaa7e8693615868e2469d7093a9e91738a1b76a01399be933988f1b3eb97",
          "sha256": "9831834618af6b85faf554775335a0a5eb5f5576c5ce285174436367621e31ca",
          "sha1": "326596026e720ccbe7e7be9e97dae66de3c6b7da",
          "md5": "9c65c46acac69ed81bebb0c39369d76f"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "waltid-dif-definitions-parser-iossimulatorarm64-1.0.0-SNAPSHOT-sources.jar",
          "url": "waltid-dif-definitions-parser-iossimulatorarm64-1.0.0-SNAPSHOT-sources.jar",
          "size": 4206,
          "sha512": "49fa058c5fb18eeb34b816e74b7b4a18cb8dab3a79e10e356e524e6b2c4d0f9b7f4c561000bbdc4b64cb5d473d9325b20a99cb3d328b7d1f90ea13f861758b45",
          "sha256": "b3f5d4572bda3784eeac814e4f98713ff3ee3ec2270d3cdb4cc7ec9d967c1c22",
          "sha1": "1d46b883513e59219052839392459971b34ef546",
          "md5": "8fe13f379f388725b84dd5c6e79904cf"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.eygraber",
          "module": "jsonpathkt-kotlinx",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.optimumcode",
          "module": "json-schema-validator",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "id.walt.credentials",
          "module": "waltid-w3c-credentials",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "waltid-dif-definitions-parser-iossimulatorarm64-1.0.0-SNAPSHOT-metadata.jar",
          "url": "waltid-dif-definitions-parser-iossimulatorarm64-1.0.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
