{
  "formatVersion": "1.1",
  "component": {
    "url": "../../waltid-mdoc-credentials/1.0.0-SNAPSHOT/waltid-mdoc-credentials-1.0.0-SNAPSHOT.module",
    "group": "id.walt.mdoc-credentials",
    "module": "waltid-mdoc-credentials",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.soywiz.korlibs.krypto",
          "module": "krypto",
          "version": {
            "requires": "4.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "waltid-mdoc-credentials-iosArm64Main-1.0.0-SNAPSHOT.klib",
          "url": "waltid-mdoc-credentials-iosarm64-1.0.0-SNAPSHOT.klib",
          "size": 413724,
          "sha512": "2438ac1425f1287c3893011707e35cc9236e87875e4f5f577d13e8f5671ca226b35926dd5dc6ead29a7d3f33229dfe4ea1f1b52ebbbfd2bd09fca95ef86125c1",
          "sha256": "e1f1e4e58d0b160117d964b52c177412254feea570451544b69790bb360dfe1d",
          "sha1": "10b69a880291a3e1570c550af9fbebc772b3312c",
          "md5": "7b72b1f7d521c46aa3c31131dd17d699"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "waltid-mdoc-credentials-iosarm64-1.0.0-SNAPSHOT-sources.jar",
          "url": "waltid-mdoc-credentials-iosarm64-1.0.0-SNAPSHOT-sources.jar",
          "size": 78133,
          "sha512": "fba54f87690c655d1a987561e2705ad5c1bd7a3b1f21f5c42366bb978acfd8dc8312852a06d2d0ba829b57fb0d1753bdb317a144de96b02112aba571d23f4af2",
          "sha256": "250b7c050d0a9f663e1a60aa5997ee9a3536d397da7c4a0863db0bd38d5c0217",
          "sha1": "a9e332e08da17664c8d14fbf17dc542d635761d7",
          "md5": "95268b64d2f8e13b105d41700a602bfe"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.soywiz.korlibs.krypto",
          "module": "krypto",
          "version": {
            "requires": "4.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "waltid-mdoc-credentials-iosarm64-1.0.0-SNAPSHOT-metadata.jar",
          "url": "waltid-mdoc-credentials-iosarm64-1.0.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
