{
  "formatVersion": "1.1",
  "component": {
    "url": "../../waltid-w3c-credentials/1.0.0-SNAPSHOT/waltid-w3c-credentials-1.0.0-SNAPSHOT.module",
    "group": "id.walt.credentials",
    "module": "waltid-w3c-credentials",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "id.walt.crypto",
          "module": "waltid-crypto",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "id.walt.sdjwt",
          "module": "waltid-sdjwt",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "id.walt.did",
          "module": "waltid-did",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "waltid-w3c-credentials-js-1.0.0-SNAPSHOT.klib",
          "url": "waltid-w3c-credentials-js-1.0.0-SNAPSHOT.klib",
          "size": 129971,
          "sha512": "5d35ffb0913eacb92eaee70fe941511fab6633fb7ea739f2e5fb1a0dc453399af65c99806a45706cd9b74acd4d6128a6e431c9a2ceb4e3c40b76498a705b07d4",
          "sha256": "570368ff1ddaac7e7d2a8fe8402cbf9d6c2e1a5980d0d27ea2dbbefaf2c04584",
          "sha1": "df1a661c3fb96f123aa4ea633535a8579b9ad141",
          "md5": "f8549feae9bd0e757b560a20fb3237ee"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "id.walt.crypto",
          "module": "waltid-crypto",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "id.walt.sdjwt",
          "module": "waltid-sdjwt",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "id.walt.did",
          "module": "waltid-did",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "love.forte.plugin.suspend-transform",
          "module": "suspend-transform-runtime-js",
          "version": {
            "requires": "2.2.20-0.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.optimumcode",
          "module": "json-schema-validator",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "app.softwork",
          "module": "kotlinx-uuid-core",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.5"
          }
        },
        {
          "group": "love.forte.plugin.suspend-transform",
          "module": "suspend-transform-annotation",
          "version": {
            "requires": "2.2.20-0.13.1"
          }
        },
        {
          "group": "love.forte.plugin.suspend-transform",
          "module": "suspend-transform-runtime",
          "version": {
            "requires": "2.2.20-0.13.1"
          }
        }
      ],
      "files": [
        {
          "name": "waltid-w3c-credentials-js-1.0.0-SNAPSHOT.klib",
          "url": "waltid-w3c-credentials-js-1.0.0-SNAPSHOT.klib",
          "size": 129971,
          "sha512": "5d35ffb0913eacb92eaee70fe941511fab6633fb7ea739f2e5fb1a0dc453399af65c99806a45706cd9b74acd4d6128a6e431c9a2ceb4e3c40b76498a705b07d4",
          "sha256": "570368ff1ddaac7e7d2a8fe8402cbf9d6c2e1a5980d0d27ea2dbbefaf2c04584",
          "sha1": "df1a661c3fb96f123aa4ea633535a8579b9ad141",
          "md5": "f8549feae9bd0e757b560a20fb3237ee"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "waltid-w3c-credentials-js-1.0.0-SNAPSHOT-sources.jar",
          "url": "waltid-w3c-credentials-js-1.0.0-SNAPSHOT-sources.jar",
          "size": 18999,
          "sha512": "5684bf9e71db15ed8ccc04d067e2db8d466cd64f5e14acb145e221c6d5c12e137102e0eb6fb124aeb8531ea5f39720f23981f548f9ac0731be5f6b32538682d5",
          "sha256": "cd8243249a2583078ddb27e77e88b8a71e6340564efe3eeb63c692aee1228e7d",
          "sha1": "51b6e40ad282855814d31ba86f85d7875ff36e00",
          "md5": "2be9e424771a432b5e544438aacbe0b5"
        }
      ]
    }
  ]
}
