{
  "formatVersion": "1.1",
  "component": {
    "url": "../../waltid-verification-policies/1.0.0-SNAPSHOT/waltid-verification-policies-1.0.0-SNAPSHOT.module",
    "group": "id.walt.policies",
    "module": "waltid-verification-policies",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "waltid-verification-policies-jvm-1.0.0-SNAPSHOT.jar",
          "url": "waltid-verification-policies-jvm-1.0.0-SNAPSHOT.jar",
          "size": 655808,
          "sha512": "fb0dab23e966d58e6f36a93f75ff33ce762cc1f0ef10ef0f8924dbd81b4b2b68fab0c1f19dd211a2cd84f6e2a8d25de125afe51bf6c061fad6c123aca18c551e",
          "sha256": "c4103b1c8d81bef4d79bd27e0e8cd97db8526021b5b9b36cdbc07861325125cc",
          "sha1": "7daaac54e2eb8fe8858ee73e9a4a0188f481e6ca",
          "md5": "e77493f79ba8df10a77e5125570342f5"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "love.forte.plugin.suspend-transform",
          "module": "suspend-transform-runtime-jvm",
          "version": {
            "requires": "2.2.20-0.13.1"
          }
        },
        {
          "group": "com.eygraber",
          "module": "jsonpathkt-kotlinx",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.optimumcode",
          "module": "json-schema-validator",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "id.walt.credentials",
          "module": "waltid-w3c-credentials",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "id.walt.dif-definitions-parser",
          "module": "waltid-dif-definitions-parser",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "id.walt.sdjwt",
          "module": "waltid-sdjwt",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.5"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "love.forte.plugin.suspend-transform",
          "module": "suspend-transform-annotation",
          "version": {
            "requires": "2.2.20-0.13.1"
          }
        },
        {
          "group": "love.forte.plugin.suspend-transform",
          "module": "suspend-transform-runtime",
          "version": {
            "requires": "2.2.20-0.13.1"
          }
        }
      ],
      "files": [
        {
          "name": "waltid-verification-policies-jvm-1.0.0-SNAPSHOT.jar",
          "url": "waltid-verification-policies-jvm-1.0.0-SNAPSHOT.jar",
          "size": 655808,
          "sha512": "fb0dab23e966d58e6f36a93f75ff33ce762cc1f0ef10ef0f8924dbd81b4b2b68fab0c1f19dd211a2cd84f6e2a8d25de125afe51bf6c061fad6c123aca18c551e",
          "sha256": "c4103b1c8d81bef4d79bd27e0e8cd97db8526021b5b9b36cdbc07861325125cc",
          "sha1": "7daaac54e2eb8fe8858ee73e9a4a0188f481e6ca",
          "md5": "e77493f79ba8df10a77e5125570342f5"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "waltid-verification-policies-jvm-1.0.0-SNAPSHOT-sources.jar",
          "url": "waltid-verification-policies-jvm-1.0.0-SNAPSHOT-sources.jar",
          "size": 51113,
          "sha512": "9499b02ff35ee7865da6ba59c81c80a650270d48408822d979bb34edae6a899ddadd4c78d3ade52714c59d72810025c978147ac5c1849f72c54452eea6fed01c",
          "sha256": "fe59188bc4c4717c2b6d441962a80f64435d545375532d758f014f8e0d391759",
          "sha1": "49806f38e61ffa0dde6a7574654b8769fdf87b5c",
          "md5": "561d92a3321ffc1a6b289f0cabbb29ed"
        }
      ]
    }
  ]
}
