{
  "formatVersion": "1.1",
  "component": {
    "url": "../../waltid-verification-policies/1.0.0-SNAPSHOT/waltid-verification-policies-1.0.0-SNAPSHOT.module",
    "group": "id.walt.policies",
    "module": "waltid-verification-policies",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "waltid-verification-policies-jvm-1.0.0-SNAPSHOT.jar",
          "url": "waltid-verification-policies-jvm-1.0.0-SNAPSHOT.jar",
          "size": 658157,
          "sha512": "8faa6f522268397d11f74638a1e01a59c298a3e4ecfe6328a6b7ee8e29c55846ef7ac75b6b691557a8328aed7be483581e66265fc6aa5a510f4d32760fc6d06e",
          "sha256": "883e7425255ed66e18a4c60e32dd876e163c1c7dfc73677046ad1ff3693aa5bb",
          "sha1": "bc55ac9ce52b5b8ab2ffe0ec8d743388440f1832",
          "md5": "a79480b6391a4ca3e50615eed1f73a7e"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "love.forte.plugin.suspend-transform",
          "module": "suspend-transform-runtime-jvm",
          "version": {
            "requires": "2.2.20-0.13.1"
          }
        },
        {
          "group": "com.eygraber",
          "module": "jsonpathkt-kotlinx",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.optimumcode",
          "module": "json-schema-validator",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "id.walt.credentials",
          "module": "waltid-w3c-credentials",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "id.walt.dif-definitions-parser",
          "module": "waltid-dif-definitions-parser",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "id.walt.sdjwt",
          "module": "waltid-sdjwt",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "id.walt.mdoc-credentials",
          "module": "waltid-mdoc-credentials",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.5"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "love.forte.plugin.suspend-transform",
          "module": "suspend-transform-annotation",
          "version": {
            "requires": "2.2.20-0.13.1"
          }
        },
        {
          "group": "love.forte.plugin.suspend-transform",
          "module": "suspend-transform-runtime",
          "version": {
            "requires": "2.2.20-0.13.1"
          }
        }
      ],
      "files": [
        {
          "name": "waltid-verification-policies-jvm-1.0.0-SNAPSHOT.jar",
          "url": "waltid-verification-policies-jvm-1.0.0-SNAPSHOT.jar",
          "size": 658157,
          "sha512": "8faa6f522268397d11f74638a1e01a59c298a3e4ecfe6328a6b7ee8e29c55846ef7ac75b6b691557a8328aed7be483581e66265fc6aa5a510f4d32760fc6d06e",
          "sha256": "883e7425255ed66e18a4c60e32dd876e163c1c7dfc73677046ad1ff3693aa5bb",
          "sha1": "bc55ac9ce52b5b8ab2ffe0ec8d743388440f1832",
          "md5": "a79480b6391a4ca3e50615eed1f73a7e"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "waltid-verification-policies-jvm-1.0.0-SNAPSHOT-sources.jar",
          "url": "waltid-verification-policies-jvm-1.0.0-SNAPSHOT-sources.jar",
          "size": 51725,
          "sha512": "740b993dc8ea88f5a304a565ec3946528d8b1e423c330c994a94e9b7981ee50203269a969cc70c2ab5f0a8fbb1d0c6dc8cd1abd2ba45171e77a0c45c347868c2",
          "sha256": "9848e1ed80b8dfc83f804e2e74a507d39201d94e23d32f73967d6fb437bc9b4f",
          "sha1": "2925b76fa5c66203d25b8002206e7b1812cec7cb",
          "md5": "46e8e89d883a56872c21524c2996bd9c"
        }
      ]
    }
  ]
}
