{
  "formatVersion": "1.1",
  "component": {
    "url": "../../waltid-crypto-ios/1.0.0-SNAPSHOT/waltid-crypto-ios-1.0.0-SNAPSHOT.module",
    "group": "id.walt.crypto",
    "module": "waltid-crypto-ios",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "id.walt.crypto",
          "module": "waltid-crypto",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "id.walt.crypto",
          "module": "waltid-target-ios",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "waltid-crypto-ios-iosArm64Main-1.0.0-SNAPSHOT.klib",
          "url": "waltid-crypto-ios-iosarm64-1.0.0-SNAPSHOT.klib",
          "size": 17421,
          "sha512": "3cd529efbf9a72424c9bf0b77fbaaf5c74fa7fe625ccdfc1470f9d53f8746239c0d058341287c33dfe65e24c08a30386d4ae9c9322d3ffe7cea68666da6eb804",
          "sha256": "1b0d11f6cab8f19148edc34b6e0707c1fc8292e1b3aa8d3140654885c55903cc",
          "sha1": "25a8f29c87632042fcb436a55c75ca6cd6af648d",
          "md5": "eae29f8dc094e07f1247da80d19549f5"
        },
        {
          "name": "waltid-crypto-ios-iosArm64Cinterop-JOSESwiftMain-1.0.0-SNAPSHOT.klib",
          "url": "waltid-crypto-ios-iosarm64-1.0.0-SNAPSHOT-cinterop-JOSESwift.klib",
          "size": 4419,
          "sha512": "cd0c0bd74d69f733696a2286001dd084e6c8775a1d11f0caeec9a957db4afcc6cf8d30a112cf04772778432215f39ef0820dc717532aaf1d7d5f0631f438c065",
          "sha256": "6d9bf3039c0b0bb7187f821ffe6ea975635c3445fac4f732c1e9dda6f86bd0be",
          "sha1": "a7b52fcf6e7faf04a3d56619d71a5e9491b7f18d",
          "md5": "3046afba80c5f7fbb0d89e6afbeb62f7"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "waltid-crypto-ios-iosarm64-1.0.0-SNAPSHOT-sources.jar",
          "url": "waltid-crypto-ios-iosarm64-1.0.0-SNAPSHOT-sources.jar",
          "size": 2258,
          "sha512": "85656b8424b4359704fb1ffc2954b8570a15f153fbabc698721aafcd92d741a5163db03d189cf330d3b1a3095ec4027658f9951011e1d804838eecb0fb87d4ac",
          "sha256": "db58faa31eb79bae7bacab4139175060b7e117406e86d487abda3ba3d0b95a6c",
          "sha1": "9248bf29f6907a10668dd58f7a627f53c54b5504",
          "md5": "eeeb371522bcfe4455d7045435296375"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "id.walt.crypto",
          "module": "waltid-crypto",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "id.walt.crypto",
          "module": "waltid-target-ios",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "waltid-crypto-ios-iosarm64-1.0.0-SNAPSHOT-metadata.jar",
          "url": "waltid-crypto-ios-iosarm64-1.0.0-SNAPSHOT-metadata.jar",
          "size": 9571,
          "sha512": "6c42f593523548835c4a1abacc879e4e32580c9a2a74a6e8c68ef9c74c8cdb1d9414f6bd6c1ba53e598f988df0c5cd8b2be4d7a50c286e74f69947bfe8c0dbbd",
          "sha256": "bcf012a24085baa6180e504da1e836537766782ae8c69839f915ee1a1fd68186",
          "sha1": "6fcd444615e243c9a47243b0a319d69758c00044",
          "md5": "3c0dff569e8e7ecff9167279334d9512"
        }
      ]
    }
  ]
}
