{
  "formatVersion": "1.1",
  "component": {
    "url": "../../waltid-verification-policies/1.0.0-SNAPSHOT/waltid-verification-policies-1.0.0-SNAPSHOT.module",
    "group": "id.walt.policies",
    "module": "waltid-verification-policies",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "waltid-verification-policies-js-1.0.0-SNAPSHOT.klib",
          "url": "waltid-verification-policies-js-1.0.0-SNAPSHOT.klib",
          "size": 251104,
          "sha512": "7802caa8812e6e0718c18363c2940d2942603614af099ac71e4b9f9e6f1a35a054fc7ccd0fcf4885655ee666e814fb989921494acd90eeddd176d4b3fe71a445",
          "sha256": "c4d095608cd0e566951c6ee3e3e4d7ddb842e4272d5886f856aba7f3a33335a4",
          "sha1": "661824b0f3b699e7352e7b318ea86262c81000ac",
          "md5": "b787c39af97593fe9a9efad461987c73"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "love.forte.plugin.suspend-transform",
          "module": "suspend-transform-runtime-js",
          "version": {
            "requires": "2.2.20-0.13.1"
          }
        },
        {
          "group": "com.eygraber",
          "module": "jsonpathkt-kotlinx",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.optimumcode",
          "module": "json-schema-validator",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "id.walt.credentials",
          "module": "waltid-w3c-credentials",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "id.walt.dif-definitions-parser",
          "module": "waltid-dif-definitions-parser",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "id.walt.sdjwt",
          "module": "waltid-sdjwt",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "id.walt.mdoc-credentials",
          "module": "waltid-mdoc-credentials",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.5"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "love.forte.plugin.suspend-transform",
          "module": "suspend-transform-annotation",
          "version": {
            "requires": "2.2.20-0.13.1"
          }
        },
        {
          "group": "love.forte.plugin.suspend-transform",
          "module": "suspend-transform-runtime",
          "version": {
            "requires": "2.2.20-0.13.1"
          }
        }
      ],
      "files": [
        {
          "name": "waltid-verification-policies-js-1.0.0-SNAPSHOT.klib",
          "url": "waltid-verification-policies-js-1.0.0-SNAPSHOT.klib",
          "size": 251104,
          "sha512": "7802caa8812e6e0718c18363c2940d2942603614af099ac71e4b9f9e6f1a35a054fc7ccd0fcf4885655ee666e814fb989921494acd90eeddd176d4b3fe71a445",
          "sha256": "c4d095608cd0e566951c6ee3e3e4d7ddb842e4272d5886f856aba7f3a33335a4",
          "sha1": "661824b0f3b699e7352e7b318ea86262c81000ac",
          "md5": "b787c39af97593fe9a9efad461987c73"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "waltid-verification-policies-js-1.0.0-SNAPSHOT-sources.jar",
          "url": "waltid-verification-policies-js-1.0.0-SNAPSHOT-sources.jar",
          "size": 31618,
          "sha512": "06f3df36f65a048170fc83c90abf8ff0995add501d28078cf6b75f8cc14ab312c9d08873886ae9cce6cb5b793fbc8d7c573c6f41927aebb99b45c03fdea48537",
          "sha256": "def3afee886ecbc0581ac4cf1d00147f4f298e2387638893ffa626d0bb2722fc",
          "sha1": "7b322be19857339c3d16cebe486c57017250b260",
          "md5": "a6304079ea77ee7b1da5d578e8d8c046"
        }
      ]
    }
  ]
}
