{
  "formatVersion": "1.1",
  "component": {
    "url": "../../waltid-verification-policies/1.0.0-SNAPSHOT/waltid-verification-policies-1.0.0-SNAPSHOT.module",
    "group": "id.walt.policies",
    "module": "waltid-verification-policies",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "waltid-verification-policies-js-1.0.0-SNAPSHOT.klib",
          "url": "waltid-verification-policies-js-1.0.0-SNAPSHOT.klib",
          "size": 251094,
          "sha512": "73617b50720af068117fbbf5aa9f6bc5314d60b340fd45bdab983486bb174205d252f05abbe24c9491d32da37988875d0b20f99c92719eefe53ebe602d169e2d",
          "sha256": "35bf417ec03052768502ed627c89cb5bbbe024b6f4c1c16e4f61ccc554e435af",
          "sha1": "31b9b215c97c007e16f2874fc328f0ce3fd62726",
          "md5": "9518a8497891cfad5379c789e10a3236"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "love.forte.plugin.suspend-transform",
          "module": "suspend-transform-runtime-js",
          "version": {
            "requires": "2.2.20-0.13.1"
          }
        },
        {
          "group": "com.eygraber",
          "module": "jsonpathkt-kotlinx",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.optimumcode",
          "module": "json-schema-validator",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "id.walt.credentials",
          "module": "waltid-w3c-credentials",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "id.walt.dif-definitions-parser",
          "module": "waltid-dif-definitions-parser",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "id.walt.sdjwt",
          "module": "waltid-sdjwt",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.5"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "love.forte.plugin.suspend-transform",
          "module": "suspend-transform-annotation",
          "version": {
            "requires": "2.2.20-0.13.1"
          }
        },
        {
          "group": "love.forte.plugin.suspend-transform",
          "module": "suspend-transform-runtime",
          "version": {
            "requires": "2.2.20-0.13.1"
          }
        }
      ],
      "files": [
        {
          "name": "waltid-verification-policies-js-1.0.0-SNAPSHOT.klib",
          "url": "waltid-verification-policies-js-1.0.0-SNAPSHOT.klib",
          "size": 251094,
          "sha512": "73617b50720af068117fbbf5aa9f6bc5314d60b340fd45bdab983486bb174205d252f05abbe24c9491d32da37988875d0b20f99c92719eefe53ebe602d169e2d",
          "sha256": "35bf417ec03052768502ed627c89cb5bbbe024b6f4c1c16e4f61ccc554e435af",
          "sha1": "31b9b215c97c007e16f2874fc328f0ce3fd62726",
          "md5": "9518a8497891cfad5379c789e10a3236"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "waltid-verification-policies-js-1.0.0-SNAPSHOT-sources.jar",
          "url": "waltid-verification-policies-js-1.0.0-SNAPSHOT-sources.jar",
          "size": 31618,
          "sha512": "06f3df36f65a048170fc83c90abf8ff0995add501d28078cf6b75f8cc14ab312c9d08873886ae9cce6cb5b793fbc8d7c573c6f41927aebb99b45c03fdea48537",
          "sha256": "def3afee886ecbc0581ac4cf1d00147f4f298e2387638893ffa626d0bb2722fc",
          "sha1": "7b322be19857339c3d16cebe486c57017250b260",
          "md5": "a6304079ea77ee7b1da5d578e8d8c046"
        }
      ]
    }
  ]
}
