{
  "formatVersion": "1.1",
  "component": {
    "group": "id.walt.crypto",
    "module": "waltid-crypto-ios",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "id.walt.crypto",
          "module": "waltid-crypto",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "id.walt.crypto",
          "module": "waltid-target-ios",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "waltid-crypto-ios-metadata-1.0.0-SNAPSHOT.jar",
          "url": "waltid-crypto-ios-1.0.0-SNAPSHOT.jar",
          "size": 749,
          "sha512": "062ba15aee59a756b8f1c9ee204b2608c076f5685d6aedda8f3c4887cb5bd0ad8feeca06d147838659a6419c0fdda03df8ce5386130149fce0b04ecbcfcf22e0",
          "sha256": "1f0bc9229abde050123359ffbca9629457d2b7449f790c44e9805468b82e601c",
          "sha1": "eba70b63c6e77670964e334b908a682f123f15d4",
          "md5": "9f1a82c4b5b0344afbfd2b128c7918ea"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "waltid-crypto-ios-kotlin-1.0.0-SNAPSHOT-sources.jar",
          "url": "waltid-crypto-ios-1.0.0-SNAPSHOT-sources.jar",
          "size": 2258,
          "sha512": "85656b8424b4359704fb1ffc2954b8570a15f153fbabc698721aafcd92d741a5163db03d189cf330d3b1a3095ec4027658f9951011e1d804838eecb0fb87d4ac",
          "sha256": "db58faa31eb79bae7bacab4139175060b7e117406e86d487abda3ba3d0b95a6c",
          "sha1": "9248bf29f6907a10668dd58f7a627f53c54b5504",
          "md5": "eeeb371522bcfe4455d7045435296375"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../waltid-crypto-ios-iosarm64/1.0.0-SNAPSHOT/waltid-crypto-ios-iosarm64-1.0.0-SNAPSHOT.module",
        "group": "id.walt.crypto",
        "module": "waltid-crypto-ios-iosarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../waltid-crypto-ios-iosarm64/1.0.0-SNAPSHOT/waltid-crypto-ios-iosarm64-1.0.0-SNAPSHOT.module",
        "group": "id.walt.crypto",
        "module": "waltid-crypto-ios-iosarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../waltid-crypto-ios-iosarm64/1.0.0-SNAPSHOT/waltid-crypto-ios-iosarm64-1.0.0-SNAPSHOT.module",
        "group": "id.walt.crypto",
        "module": "waltid-crypto-ios-iosarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../waltid-crypto-ios-iossimulatorarm64/1.0.0-SNAPSHOT/waltid-crypto-ios-iossimulatorarm64-1.0.0-SNAPSHOT.module",
        "group": "id.walt.crypto",
        "module": "waltid-crypto-ios-iossimulatorarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../waltid-crypto-ios-iossimulatorarm64/1.0.0-SNAPSHOT/waltid-crypto-ios-iossimulatorarm64-1.0.0-SNAPSHOT.module",
        "group": "id.walt.crypto",
        "module": "waltid-crypto-ios-iossimulatorarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../waltid-crypto-ios-iossimulatorarm64/1.0.0-SNAPSHOT/waltid-crypto-ios-iossimulatorarm64-1.0.0-SNAPSHOT.module",
        "group": "id.walt.crypto",
        "module": "waltid-crypto-ios-iossimulatorarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    }
  ]
}
