{
  "formatVersion": "1.1",
  "component": {
    "url": "../../waltid-openid4vc/1.0.0-SNAPSHOT/waltid-openid4vc-1.0.0-SNAPSHOT.module",
    "group": "id.walt.openid4vc",
    "module": "waltid-openid4vc",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "waltid-openid4vc-js-1.0.0-SNAPSHOT.klib",
          "url": "waltid-openid4vc-js-1.0.0-SNAPSHOT.klib",
          "size": 765051,
          "sha512": "100e88e1c6ac28b93d069fb5f6b66a06106e3a852fd02780bf0f19264c421cb2a2c677f410c3549c06930b6a8c086a7bbdc05bb91cc14262e61f207d7404cece",
          "sha256": "3a064e54a45b6a2b1dca87514a12acc9fd4760d888e0c75b648651d47d0ad4bf",
          "sha1": "a04c40d5dfa7820806cadc5923808a76bbc8a6ff",
          "md5": "d11b66f3270cb031c40ca5ad43d57d17"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-js",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.5"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "id.walt.crypto",
          "module": "waltid-crypto",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "id.walt.mdoc-credentials",
          "module": "waltid-mdoc-credentials",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "id.walt.credentials",
          "module": "waltid-w3c-credentials",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "id.walt.policies",
          "module": "waltid-verification-policies",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "id.walt.sdjwt",
          "module": "waltid-sdjwt",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "id.walt.did",
          "module": "waltid-did",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "app.softwork",
          "module": "kotlinx-uuid-core",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.kotlincrypto.hash",
          "module": "bom",
          "version": {
            "requires": "0.6.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.kotlincrypto.hash",
          "module": "sha2"
        }
      ],
      "files": [
        {
          "name": "waltid-openid4vc-js-1.0.0-SNAPSHOT.klib",
          "url": "waltid-openid4vc-js-1.0.0-SNAPSHOT.klib",
          "size": 765051,
          "sha512": "100e88e1c6ac28b93d069fb5f6b66a06106e3a852fd02780bf0f19264c421cb2a2c677f410c3549c06930b6a8c086a7bbdc05bb91cc14262e61f207d7404cece",
          "sha256": "3a064e54a45b6a2b1dca87514a12acc9fd4760d888e0c75b648651d47d0ad4bf",
          "sha1": "a04c40d5dfa7820806cadc5923808a76bbc8a6ff",
          "md5": "d11b66f3270cb031c40ca5ad43d57d17"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "waltid-openid4vc-js-1.0.0-SNAPSHOT-sources.jar",
          "url": "waltid-openid4vc-js-1.0.0-SNAPSHOT-sources.jar",
          "size": 100860,
          "sha512": "a1b317881cf84660a3ccff08fc12a596be9a5b23de502c90ea8a2c3e9691d717d884872d5401aeadcfe4337e23b14681cb9dcb2c375944647f0797655d20ff83",
          "sha256": "7d855f67eb69342d490a9b7994ade4d2934e5bdd5e92e32f8036bb9991359066",
          "sha1": "12c1cbc4e7062e39bac5549b12028c16e1cd43e0",
          "md5": "fd7a8d0b9bd70ab231d155b6549b849a"
        }
      ]
    }
  ]
}
