{
  "formatVersion": "1.1",
  "component": {
    "group": "id.walt.credentials",
    "module": "waltid-w3c-credentials",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "id.walt.crypto",
          "module": "waltid-crypto",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "id.walt.sdjwt",
          "module": "waltid-sdjwt",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "id.walt.did",
          "module": "waltid-did",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "love.forte.plugin.suspend-transform",
          "module": "suspend-transform-runtime",
          "version": {
            "requires": "2.2.20-0.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.optimumcode",
          "module": "json-schema-validator",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "app.softwork",
          "module": "kotlinx-uuid-core",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.5"
          }
        },
        {
          "group": "love.forte.plugin.suspend-transform",
          "module": "suspend-transform-annotation",
          "version": {
            "requires": "2.2.20-0.13.1"
          }
        }
      ],
      "files": [
        {
          "name": "waltid-w3c-credentials-1.0.0-SNAPSHOT.jar",
          "url": "waltid-w3c-credentials-1.0.0-SNAPSHOT.jar",
          "size": 19475,
          "sha512": "745eaa5bfd6c5f26d3348e19f84e36208a85de2f78ffe0fee759eaa51594a688282cc46e047265b2276022b9fe1c49f454b8a726d4c5008532933322f2af71d8",
          "sha256": "644bd4e4abfd07e83dea650cca8156937650658baf525925455f76db2048bfb8",
          "sha1": "3b26832789e2d5ed9623153d441d5d2012903ee4",
          "md5": "67a5c9db887852c14ea436b9c9113280"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "waltid-w3c-credentials-1.0.0-SNAPSHOT-sources.jar",
          "url": "waltid-w3c-credentials-1.0.0-SNAPSHOT-sources.jar",
          "size": 18069,
          "sha512": "c3c773e87940d32e12c6f385a4c7baf945cad8ebaf360aaae8d239b6892cd135d59bb894722b330bebfc5c48a61615e7c41c500165f7bc5d5a7d211d292dfdef",
          "sha256": "44830bb02aef67264cc68e258312ac878e1bc104e47eac33cb6c9205984d8372",
          "sha1": "81e8150b14f8741b7c26290a2a566949f9fbea23",
          "md5": "c9e844347e2dff61fa12f9b4b4254fd9"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../waltid-w3c-credentials-iosarm64/1.0.0-SNAPSHOT/waltid-w3c-credentials-iosarm64-1.0.0-SNAPSHOT.module",
        "group": "id.walt.credentials",
        "module": "waltid-w3c-credentials-iosarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../waltid-w3c-credentials-iosarm64/1.0.0-SNAPSHOT/waltid-w3c-credentials-iosarm64-1.0.0-SNAPSHOT.module",
        "group": "id.walt.credentials",
        "module": "waltid-w3c-credentials-iosarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../waltid-w3c-credentials-iosarm64/1.0.0-SNAPSHOT/waltid-w3c-credentials-iosarm64-1.0.0-SNAPSHOT.module",
        "group": "id.walt.credentials",
        "module": "waltid-w3c-credentials-iosarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../waltid-w3c-credentials-iossimulatorarm64/1.0.0-SNAPSHOT/waltid-w3c-credentials-iossimulatorarm64-1.0.0-SNAPSHOT.module",
        "group": "id.walt.credentials",
        "module": "waltid-w3c-credentials-iossimulatorarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../waltid-w3c-credentials-iossimulatorarm64/1.0.0-SNAPSHOT/waltid-w3c-credentials-iossimulatorarm64-1.0.0-SNAPSHOT.module",
        "group": "id.walt.credentials",
        "module": "waltid-w3c-credentials-iossimulatorarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../waltid-w3c-credentials-iossimulatorarm64/1.0.0-SNAPSHOT/waltid-w3c-credentials-iossimulatorarm64-1.0.0-SNAPSHOT.module",
        "group": "id.walt.credentials",
        "module": "waltid-w3c-credentials-iossimulatorarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../waltid-w3c-credentials-js/1.0.0-SNAPSHOT/waltid-w3c-credentials-js-1.0.0-SNAPSHOT.module",
        "group": "id.walt.credentials",
        "module": "waltid-w3c-credentials-js",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../waltid-w3c-credentials-js/1.0.0-SNAPSHOT/waltid-w3c-credentials-js-1.0.0-SNAPSHOT.module",
        "group": "id.walt.credentials",
        "module": "waltid-w3c-credentials-js",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../waltid-w3c-credentials-js/1.0.0-SNAPSHOT/waltid-w3c-credentials-js-1.0.0-SNAPSHOT.module",
        "group": "id.walt.credentials",
        "module": "waltid-w3c-credentials-js",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../waltid-w3c-credentials-jvm/1.0.0-SNAPSHOT/waltid-w3c-credentials-jvm-1.0.0-SNAPSHOT.module",
        "group": "id.walt.credentials",
        "module": "waltid-w3c-credentials-jvm",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../waltid-w3c-credentials-jvm/1.0.0-SNAPSHOT/waltid-w3c-credentials-jvm-1.0.0-SNAPSHOT.module",
        "group": "id.walt.credentials",
        "module": "waltid-w3c-credentials-jvm",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../waltid-w3c-credentials-jvm/1.0.0-SNAPSHOT/waltid-w3c-credentials-jvm-1.0.0-SNAPSHOT.module",
        "group": "id.walt.credentials",
        "module": "waltid-w3c-credentials-jvm",
        "version": "1.0.0-SNAPSHOT"
      }
    }
  ]
}
