{
  "formatVersion": "1.1",
  "component": {
    "url": "../../waltid-cose/1.0.0-SNAPSHOT/waltid-cose-1.0.0-SNAPSHOT.module",
    "group": "id.walt.crypto",
    "module": "waltid-cose",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "waltid-cose-js-1.0.0-SNAPSHOT.klib",
          "url": "waltid-cose-js-1.0.0-SNAPSHOT.klib",
          "size": 83287,
          "sha512": "e98fd4ba857d04cbe65df977af835423bc424d4c714e531874b1167c3c674097843c9ae9eada76b839112bad19c80372de8e84685e43ff2fc394edf82f99c004",
          "sha256": "925caa83e2f3bddfb13dd17c2f8925555a69ae6be0f88f63572bea6abbbdea55",
          "sha1": "5b75cc63c2f1e309347325b487b3f546b355611c",
          "md5": "9907eefd503f439b2316c7f88afb31bf"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-cbor",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "id.walt.crypto",
          "module": "waltid-crypto",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.kotlincrypto.macs",
          "module": "bom",
          "version": {
            "requires": "0.7.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.kotlincrypto.macs",
          "module": "hmac-sha2"
        }
      ],
      "files": [
        {
          "name": "waltid-cose-js-1.0.0-SNAPSHOT.klib",
          "url": "waltid-cose-js-1.0.0-SNAPSHOT.klib",
          "size": 83287,
          "sha512": "e98fd4ba857d04cbe65df977af835423bc424d4c714e531874b1167c3c674097843c9ae9eada76b839112bad19c80372de8e84685e43ff2fc394edf82f99c004",
          "sha256": "925caa83e2f3bddfb13dd17c2f8925555a69ae6be0f88f63572bea6abbbdea55",
          "sha1": "5b75cc63c2f1e309347325b487b3f546b355611c",
          "md5": "9907eefd503f439b2316c7f88afb31bf"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "waltid-cose-js-1.0.0-SNAPSHOT-sources.jar",
          "url": "waltid-cose-js-1.0.0-SNAPSHOT-sources.jar",
          "size": 10998,
          "sha512": "a6f49c30b3716ee09e51c627ac9ada99e2fbf4e2101fa2436406e8220272ddacade78204003cc7f034134d2e96e68c207f49d206d835000a50459abdf489c021",
          "sha256": "387b323c5267b3b77988067e53f1d25dd16cbbc3d2bc1668e41ae16b05ebefb4",
          "sha1": "50def13982504f5ac134047d1362641dca8184ea",
          "md5": "0db79373423c90600906436e451eb7f0"
        }
      ]
    }
  ]
}
