{
  "formatVersion": "1.1",
  "component": {
    "url": "../../waltid-cose/1.0.0-SNAPSHOT/waltid-cose-1.0.0-SNAPSHOT.module",
    "group": "id.walt.crypto",
    "module": "waltid-cose",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "waltid-cose-js-1.0.0-SNAPSHOT.klib",
          "url": "waltid-cose-js-1.0.0-SNAPSHOT.klib",
          "size": 85272,
          "sha512": "fa008a756f473107ff6dbb542b7ed5100a1f54ff782e8a19d005efc8f5705a620e8e4f40b04fdf3a4b39157b91f4be0baeb0c796569008e5db5eb9f25360d839",
          "sha256": "612446ee50d908c633aaa5bea9058353bcfb15838934fdc9aff2dc1cd52481cb",
          "sha1": "1746c182c9562c0ac0f25dc53fd2a99fb8df2e26",
          "md5": "d3db1aa9ed716c1896f48e80d54b710f"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.5"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-cbor",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "id.walt.crypto",
          "module": "waltid-crypto",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.kotlincrypto.macs",
          "module": "bom",
          "version": {
            "requires": "0.7.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.kotlincrypto.macs",
          "module": "hmac-sha2"
        }
      ],
      "files": [
        {
          "name": "waltid-cose-js-1.0.0-SNAPSHOT.klib",
          "url": "waltid-cose-js-1.0.0-SNAPSHOT.klib",
          "size": 85272,
          "sha512": "fa008a756f473107ff6dbb542b7ed5100a1f54ff782e8a19d005efc8f5705a620e8e4f40b04fdf3a4b39157b91f4be0baeb0c796569008e5db5eb9f25360d839",
          "sha256": "612446ee50d908c633aaa5bea9058353bcfb15838934fdc9aff2dc1cd52481cb",
          "sha1": "1746c182c9562c0ac0f25dc53fd2a99fb8df2e26",
          "md5": "d3db1aa9ed716c1896f48e80d54b710f"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "waltid-cose-js-1.0.0-SNAPSHOT-sources.jar",
          "url": "waltid-cose-js-1.0.0-SNAPSHOT-sources.jar",
          "size": 11276,
          "sha512": "69fd8740da6dbd418095ddc8f67bdc315ff48bb75630561151613920ae4f5a9209e7a39af207351fd9ee0e6ed7122aa2f03dde4c5719fd10de0f9a6c9a7ed76b",
          "sha256": "1cf2f3de48cce77f7ea04a373873f43a6d9fe1aa325ca21d2732c7a45b87943c",
          "sha1": "8c7efc19dfc8969337b19e8228b1189f10c31d48",
          "md5": "ce5c42c4dce5b486b028e86aef5a7442"
        }
      ]
    }
  ]
}
