{
  "formatVersion": "1.1",
  "component": {
    "url": "../../waltid-crypto/1.0.0-SNAPSHOT/waltid-crypto-1.0.0-SNAPSHOT.module",
    "group": "id.walt.crypto",
    "module": "waltid-crypto",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "love.forte.plugin.suspend-transform",
          "module": "suspend-transform-runtime",
          "version": {
            "requires": "2.2.20-0.13.1"
          }
        },
        {
          "group": "id.walt.crypto",
          "module": "waltid-target-ios",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.kotlincrypto.hash",
          "module": "bom",
          "version": {
            "requires": "0.6.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.kotlincrypto.hash",
          "module": "sha2"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.github.reactivecircus.cache4k",
          "module": "cache4k",
          "version": {
            "requires": "0.14.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.5"
          }
        },
        {
          "group": "love.forte.plugin.suspend-transform",
          "module": "suspend-transform-annotation",
          "version": {
            "requires": "2.2.20-0.13.1"
          }
        },
        {
          "group": "org.kotlincrypto.macs",
          "module": "bom",
          "version": {
            "requires": "0.6.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.kotlincrypto.macs",
          "module": "hmac-sha2"
        }
      ],
      "files": [
        {
          "name": "waltid-crypto-iosSimulatorArm64Main-1.0.0-SNAPSHOT.klib",
          "url": "waltid-crypto-iossimulatorarm64-1.0.0-SNAPSHOT.klib",
          "size": 331398,
          "sha512": "b7c5b56c13ca745c7be789d71ef72f041bcdd8eb04412e2e5bf2ddb6e8ba637f5cf3535efa0383fef966c97eb91070ac62986f6fd1b69e49bdf1f4dc07920dec",
          "sha256": "a7cf8886068383666c542ac94a8e7a564eae9c562cf1a47580328ed00c619266",
          "sha1": "05c6dec60a041cbe36b1fa474e158e4399f348e8",
          "md5": "b989e675c4a75d627c1f1755a1947128"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "waltid-crypto-iossimulatorarm64-1.0.0-SNAPSHOT-sources.jar",
          "url": "waltid-crypto-iossimulatorarm64-1.0.0-SNAPSHOT-sources.jar",
          "size": 54191,
          "sha512": "1ef0f04e3d1c19a7dbfe28b9d93761e00e7bd01522af5553540c725a7e72c4ecae428ad5da55fb0d2857ef35bf7ad9c76f5bac73a4fb6f89cb9d9472c79d4eaf",
          "sha256": "0543f1e81a6bf56778800a37d539d0a73284688b4b4b54801ebc22f227a19f54",
          "sha1": "387498867053ed7e846712e6d0f1dcc671762868",
          "md5": "359eae6d7a8ee399d77d7ffa340fd3f2"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "love.forte.plugin.suspend-transform",
          "module": "suspend-transform-runtime",
          "version": {
            "requires": "2.2.20-0.13.1"
          }
        },
        {
          "group": "id.walt.crypto",
          "module": "waltid-target-ios",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.kotlincrypto.hash",
          "module": "bom",
          "version": {
            "requires": "0.6.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.kotlincrypto.hash",
          "module": "sha2"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.github.reactivecircus.cache4k",
          "module": "cache4k",
          "version": {
            "requires": "0.14.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.5"
          }
        },
        {
          "group": "love.forte.plugin.suspend-transform",
          "module": "suspend-transform-annotation",
          "version": {
            "requires": "2.2.20-0.13.1"
          }
        },
        {
          "group": "org.kotlincrypto.macs",
          "module": "bom",
          "version": {
            "requires": "0.6.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.kotlincrypto.macs",
          "module": "hmac-sha2"
        }
      ],
      "files": [
        {
          "name": "waltid-crypto-iossimulatorarm64-1.0.0-SNAPSHOT-metadata.jar",
          "url": "waltid-crypto-iossimulatorarm64-1.0.0-SNAPSHOT-metadata.jar",
          "size": 5273,
          "sha512": "1938a76b9dca80f8647002880f7b52f28715e840c5e2a16bb33e3a9df40edeadf33eecb210a2ce2dca1d02e0b2029e6476109564e2451ccc83d4c9832768bd65",
          "sha256": "787d91ce83038bd91f529c9e14bb1ad19c601eea4d49dd325d87fdd9b3670716",
          "sha1": "84015090a740badc41f4a8dc7343b9c7f586330d",
          "md5": "5afe0397c6ab683c83b21aadde039706"
        }
      ]
    }
  ]
}
