{
  "formatVersion": "1.1",
  "component": {
    "url": "../../waltid-did/1.0.0-SNAPSHOT/waltid-did-1.0.0-SNAPSHOT.module",
    "group": "id.walt.did",
    "module": "waltid-did",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "id.walt.crypto",
          "module": "waltid-crypto",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "waltid-did-jvm-1.0.0-SNAPSHOT.jar",
          "url": "waltid-did-jvm-1.0.0-SNAPSHOT.jar",
          "size": 790346,
          "sha512": "f514725b70a1202b64e630e91012fac6cd9e07c4eb3c5f72cddf004f44430c981bf34ff3785cced53102ee0e6ff6e7cb1c86788e38ecf3a3f0ec52c33e29d6c1",
          "sha256": "858b0e33c238f6aa4266913c2478e5510dad62150ba21ffb1d2ff5c276b060e6",
          "sha1": "5c84a0e7a2a7bd0acf0d91538ee1f53dd120b45f",
          "md5": "54de74f5f366eecd6672ab8878e5a423"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "id.walt.crypto",
          "module": "waltid-crypto",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.github.erdtman",
          "module": "java-json-canonicalization",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "love.forte.plugin.suspend-transform",
          "module": "suspend-transform-runtime-jvm",
          "version": {
            "requires": "2.2.20-0.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "app.softwork",
          "module": "kotlinx-uuid-core",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "net.thauvin.erik.urlencoder",
          "module": "urlencoder-lib",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.5"
          }
        },
        {
          "group": "love.forte.plugin.suspend-transform",
          "module": "suspend-transform-annotation",
          "version": {
            "requires": "2.2.20-0.13.1"
          }
        },
        {
          "group": "love.forte.plugin.suspend-transform",
          "module": "suspend-transform-runtime",
          "version": {
            "requires": "2.2.20-0.13.1"
          }
        }
      ],
      "files": [
        {
          "name": "waltid-did-jvm-1.0.0-SNAPSHOT.jar",
          "url": "waltid-did-jvm-1.0.0-SNAPSHOT.jar",
          "size": 790346,
          "sha512": "f514725b70a1202b64e630e91012fac6cd9e07c4eb3c5f72cddf004f44430c981bf34ff3785cced53102ee0e6ff6e7cb1c86788e38ecf3a3f0ec52c33e29d6c1",
          "sha256": "858b0e33c238f6aa4266913c2478e5510dad62150ba21ffb1d2ff5c276b060e6",
          "sha1": "5c84a0e7a2a7bd0acf0d91538ee1f53dd120b45f",
          "md5": "54de74f5f366eecd6672ab8878e5a423"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "waltid-did-jvm-1.0.0-SNAPSHOT-sources.jar",
          "url": "waltid-did-jvm-1.0.0-SNAPSHOT-sources.jar",
          "size": 63371,
          "sha512": "430ef317f60c363fb4be84fc5ae681e1ba53c9d61e36e55e9c264ba5e2fc56c906cb388ca8d34ef03e6aa7d5d6bb842b2babb6ad282ff2e8c602dd49ced68933",
          "sha256": "f0b6e202149ecb642c2006e5af5a544c513266d811dd31b3145c972af4298549",
          "sha1": "bce237560f839f38c4f5418fa39d63d056059019",
          "md5": "025909f736b9e8576a4aeb38a8f0e9d2"
        }
      ]
    }
  ]
}
