{
  "formatVersion": "1.1",
  "component": {
    "group": "id.walt.crypto",
    "module": "waltid-crypto",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "id.walt.crypto",
          "module": "waltid-target-ios",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "love.forte.plugin.suspend-transform",
          "module": "suspend-transform-runtime",
          "version": {
            "requires": "2.2.20-0.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.kotlincrypto.hash",
          "module": "bom",
          "version": {
            "requires": "0.6.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.kotlincrypto.hash",
          "module": "sha2"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.github.reactivecircus.cache4k",
          "module": "cache4k",
          "version": {
            "requires": "0.14.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.5"
          }
        },
        {
          "group": "love.forte.plugin.suspend-transform",
          "module": "suspend-transform-annotation",
          "version": {
            "requires": "2.2.20-0.13.1"
          }
        },
        {
          "group": "org.kotlincrypto.macs",
          "module": "bom",
          "version": {
            "requires": "0.6.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.kotlincrypto.macs",
          "module": "hmac-sha2"
        }
      ],
      "files": [
        {
          "name": "waltid-crypto-1.0.0-SNAPSHOT.jar",
          "url": "waltid-crypto-1.0.0-SNAPSHOT.jar",
          "size": 41181,
          "sha512": "1ad60b4cac2803b886381b267144654eb468c59927ec031a6770e6b6b9a0f82c2746cc5f30b201526b06a44cbe95293889cd169a79ec087d26ec4cb89cf9222e",
          "sha256": "5f1e51932f84a4b799546e44ce567322ed977a444bbccfd3eb7763f42f30c99f",
          "sha1": "ec89e4b9903304e9158e90430402ff0a25d6e5c6",
          "md5": "b3ac57e0f60125bdcd250d8d0d1fedf5"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "waltid-crypto-1.0.0-SNAPSHOT-sources.jar",
          "url": "waltid-crypto-1.0.0-SNAPSHOT-sources.jar",
          "size": 54191,
          "sha512": "58d854ae2c9d6efb7a987f021bf0a258eff38c48f59131b121aa86faf57c18a30d306e92e20d15f8a562df694e45bd875b53f7b27c43d1605ac8c6510ae9c0b1",
          "sha256": "1d27dacaecee8fe83361a930ece2cd7b1f5f6489b1916fcc62f9af9566781c0f",
          "sha1": "139b20436adeece5dbed35c2b9d0fa9158ed7bbf",
          "md5": "8e27f0df43b7563e9e3432b72c3b904f"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../waltid-crypto-iosarm64/1.0.0-SNAPSHOT/waltid-crypto-iosarm64-1.0.0-SNAPSHOT.module",
        "group": "id.walt.crypto",
        "module": "waltid-crypto-iosarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../waltid-crypto-iosarm64/1.0.0-SNAPSHOT/waltid-crypto-iosarm64-1.0.0-SNAPSHOT.module",
        "group": "id.walt.crypto",
        "module": "waltid-crypto-iosarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../waltid-crypto-iosarm64/1.0.0-SNAPSHOT/waltid-crypto-iosarm64-1.0.0-SNAPSHOT.module",
        "group": "id.walt.crypto",
        "module": "waltid-crypto-iosarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../waltid-crypto-iossimulatorarm64/1.0.0-SNAPSHOT/waltid-crypto-iossimulatorarm64-1.0.0-SNAPSHOT.module",
        "group": "id.walt.crypto",
        "module": "waltid-crypto-iossimulatorarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../waltid-crypto-iossimulatorarm64/1.0.0-SNAPSHOT/waltid-crypto-iossimulatorarm64-1.0.0-SNAPSHOT.module",
        "group": "id.walt.crypto",
        "module": "waltid-crypto-iossimulatorarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../waltid-crypto-iossimulatorarm64/1.0.0-SNAPSHOT/waltid-crypto-iossimulatorarm64-1.0.0-SNAPSHOT.module",
        "group": "id.walt.crypto",
        "module": "waltid-crypto-iossimulatorarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../waltid-crypto-js/1.0.0-SNAPSHOT/waltid-crypto-js-1.0.0-SNAPSHOT.module",
        "group": "id.walt.crypto",
        "module": "waltid-crypto-js",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../waltid-crypto-js/1.0.0-SNAPSHOT/waltid-crypto-js-1.0.0-SNAPSHOT.module",
        "group": "id.walt.crypto",
        "module": "waltid-crypto-js",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../waltid-crypto-js/1.0.0-SNAPSHOT/waltid-crypto-js-1.0.0-SNAPSHOT.module",
        "group": "id.walt.crypto",
        "module": "waltid-crypto-js",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../waltid-crypto-jvm/1.0.0-SNAPSHOT/waltid-crypto-jvm-1.0.0-SNAPSHOT.module",
        "group": "id.walt.crypto",
        "module": "waltid-crypto-jvm",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../waltid-crypto-jvm/1.0.0-SNAPSHOT/waltid-crypto-jvm-1.0.0-SNAPSHOT.module",
        "group": "id.walt.crypto",
        "module": "waltid-crypto-jvm",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../waltid-crypto-jvm/1.0.0-SNAPSHOT/waltid-crypto-jvm-1.0.0-SNAPSHOT.module",
        "group": "id.walt.crypto",
        "module": "waltid-crypto-jvm",
        "version": "1.0.0-SNAPSHOT"
      }
    }
  ]
}
