{
  "formatVersion": "1.1",
  "component": {
    "url": "../../waltid-crypto/1.0.0-SNAPSHOT/waltid-crypto-1.0.0-SNAPSHOT.module",
    "group": "id.walt.crypto",
    "module": "waltid-crypto",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "waltid-crypto-js-1.0.0-SNAPSHOT.klib",
          "url": "waltid-crypto-js-1.0.0-SNAPSHOT.klib",
          "size": 430226,
          "sha512": "f98dbf2eee2facc3ad51a105a05e0a5e3e00e68d9d167e752cc1f68c71477af544a39887921fd442c89ff3e87510effd47fc7cd4e9659c59f77c75e37d870815",
          "sha256": "7332f1044d7f941f2efc080da9e37cb2cdbefd0e5d6c92b7c780d6d727c6b291",
          "sha1": "c0007200275456c81ab14bc1d62ae2f68d81e9f8",
          "md5": "d85b17c77139e1c8d129301aee054fe2"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "love.forte.plugin.suspend-transform",
          "module": "suspend-transform-runtime-js",
          "version": {
            "requires": "2.2.20-0.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.kotlincrypto.hash",
          "module": "bom",
          "version": {
            "requires": "0.6.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.kotlincrypto.hash",
          "module": "sha2"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.github.reactivecircus.cache4k",
          "module": "cache4k",
          "version": {
            "requires": "0.14.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.5"
          }
        },
        {
          "group": "love.forte.plugin.suspend-transform",
          "module": "suspend-transform-annotation",
          "version": {
            "requires": "2.2.20-0.13.1"
          }
        },
        {
          "group": "org.kotlincrypto.macs",
          "module": "bom",
          "version": {
            "requires": "0.6.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.kotlincrypto.macs",
          "module": "hmac-sha2"
        },
        {
          "group": "love.forte.plugin.suspend-transform",
          "module": "suspend-transform-runtime",
          "version": {
            "requires": "2.2.20-0.13.1"
          }
        }
      ],
      "files": [
        {
          "name": "waltid-crypto-js-1.0.0-SNAPSHOT.klib",
          "url": "waltid-crypto-js-1.0.0-SNAPSHOT.klib",
          "size": 430226,
          "sha512": "f98dbf2eee2facc3ad51a105a05e0a5e3e00e68d9d167e752cc1f68c71477af544a39887921fd442c89ff3e87510effd47fc7cd4e9659c59f77c75e37d870815",
          "sha256": "7332f1044d7f941f2efc080da9e37cb2cdbefd0e5d6c92b7c780d6d727c6b291",
          "sha1": "c0007200275456c81ab14bc1d62ae2f68d81e9f8",
          "md5": "d85b17c77139e1c8d129301aee054fe2"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "waltid-crypto-js-1.0.0-SNAPSHOT-sources.jar",
          "url": "waltid-crypto-js-1.0.0-SNAPSHOT-sources.jar",
          "size": 68869,
          "sha512": "8dffae900542b09143f2becd1726fc48614c0fcbab2230b55bb3059e2a3efe6be0692ebfc0dbb958eae0f200f633aa4f1820e9600af86069dbba484de532bbd1",
          "sha256": "771f79ab374514403c1f62546c1441002aa2ba1d9bdb816b7e5fcaa2be0be6a1",
          "sha1": "ad6f8fd65e94f6709327b5f013cf5d91fc096a5d",
          "md5": "0d63e63d3da74c50ee4f1884661023eb"
        }
      ]
    }
  ]
}
