{
  "formatVersion": "1.1",
  "component": {
    "url": "../../waltid-crypto-ios/1.0.0-SNAPSHOT/waltid-crypto-ios-1.0.0-SNAPSHOT.module",
    "group": "id.walt.crypto",
    "module": "waltid-crypto-ios",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "id.walt.crypto",
          "module": "waltid-crypto",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "id.walt.crypto",
          "module": "waltid-target-ios",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "waltid-crypto-ios-iosSimulatorArm64Main-1.0.0-SNAPSHOT.klib",
          "url": "waltid-crypto-ios-iossimulatorarm64-1.0.0-SNAPSHOT.klib",
          "size": 17486,
          "sha512": "f51ee79a87f815d3f6232f86c3ea366de68221648c9216ad67c4dc4ae3eb1516b165be5e1fd9bf6a41bfa3f798cda0d35e9eed106446238915a1ddf7f6463519",
          "sha256": "ea1fea9b9c4fe5da3dda0c988636bb144567271009cdc7c95d44726e8133b10a",
          "sha1": "f37c0eee5b5ba97094c467a75ab73b3802a2d45c",
          "md5": "6edc157879692ff6fb756f17e9d69c4c"
        },
        {
          "name": "waltid-crypto-ios-iosSimulatorArm64Cinterop-JOSESwiftMain-1.0.0-SNAPSHOT.klib",
          "url": "waltid-crypto-ios-iossimulatorarm64-1.0.0-SNAPSHOT-cinterop-JOSESwift.klib",
          "size": 4530,
          "sha512": "b2ca6d52baa771a01b2bfff7c1eaf0de25cdc8e2548ef75055e29c9866a2a25acb91d7d85f82f65cd39b4de72ad580b709279c38e66501a3df6e8921e0bb3800",
          "sha256": "32762687aa8f5d048fcf64abb570aac0e6e5ee0e3c586e8f20318d457d67fbab",
          "sha1": "6f82058d04694dd1d257ea475a36395c6aa89718",
          "md5": "e7a847d6eeb32bd1b53c0cbf701ac7e8"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "waltid-crypto-ios-iossimulatorarm64-1.0.0-SNAPSHOT-sources.jar",
          "url": "waltid-crypto-ios-iossimulatorarm64-1.0.0-SNAPSHOT-sources.jar",
          "size": 2258,
          "sha512": "85656b8424b4359704fb1ffc2954b8570a15f153fbabc698721aafcd92d741a5163db03d189cf330d3b1a3095ec4027658f9951011e1d804838eecb0fb87d4ac",
          "sha256": "db58faa31eb79bae7bacab4139175060b7e117406e86d487abda3ba3d0b95a6c",
          "sha1": "9248bf29f6907a10668dd58f7a627f53c54b5504",
          "md5": "eeeb371522bcfe4455d7045435296375"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "id.walt.crypto",
          "module": "waltid-crypto",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "id.walt.crypto",
          "module": "waltid-target-ios",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "waltid-crypto-ios-iossimulatorarm64-1.0.0-SNAPSHOT-metadata.jar",
          "url": "waltid-crypto-ios-iossimulatorarm64-1.0.0-SNAPSHOT-metadata.jar",
          "size": 9571,
          "sha512": "6c42f593523548835c4a1abacc879e4e32580c9a2a74a6e8c68ef9c74c8cdb1d9414f6bd6c1ba53e598f988df0c5cd8b2be4d7a50c286e74f69947bfe8c0dbbd",
          "sha256": "bcf012a24085baa6180e504da1e836537766782ae8c69839f915ee1a1fd68186",
          "sha1": "6fcd444615e243c9a47243b0a319d69758c00044",
          "md5": "3c0dff569e8e7ecff9167279334d9512"
        }
      ]
    }
  ]
}
