{
  "formatVersion": "1.1",
  "component": {
    "url": "../../waltid-mdoc-credentials2/1.0.0-SNAPSHOT/waltid-mdoc-credentials2-1.0.0-SNAPSHOT.module",
    "group": "id.walt.credentials",
    "module": "waltid-mdoc-credentials2",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "id.walt.crypto",
          "module": "waltid-cose",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "waltid-mdoc-credentials2-jvm-1.0.0-SNAPSHOT.jar",
          "url": "waltid-mdoc-credentials2-jvm-1.0.0-SNAPSHOT.jar",
          "size": 490310,
          "sha512": "ba0e52cb1f965b36885d8aa80efe68c9152b2923ee176960a139bb45c3af8182072ed5b0f225074857c7d8c780db1549bd233314e98a27f2e9c9c9d33ddfc5b8",
          "sha256": "5ab0b39f39b8f409243e5aa7741b03e4eef41968e959ab9b0bc66b3431b0ee07",
          "sha1": "afd41f5ad8ba402787f6a509fba3c32acd1dddb4",
          "md5": "69fda835fa8e427d11570b26bf2bca6a"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "id.walt.crypto",
          "module": "waltid-cose",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.13"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "app.softwork",
          "module": "kotlinx-uuid-core",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.eygraber",
          "module": "jsonpathkt-kotlinx",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-cbor",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "net.orandja.obor",
          "module": "obor",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "org.kotlincrypto.random",
          "module": "crypto-rand",
          "version": {
            "requires": "0.5.2"
          }
        },
        {
          "group": "org.kotlincrypto.hash",
          "module": "bom",
          "version": {
            "requires": "0.7.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.kotlincrypto.hash",
          "module": "sha2"
        },
        {
          "group": "org.kotlincrypto.macs",
          "module": "bom",
          "version": {
            "requires": "0.7.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.kotlincrypto.macs",
          "module": "hmac-sha2"
        },
        {
          "group": "id.walt.crypto",
          "module": "waltid-crypto",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "waltid-mdoc-credentials2-jvm-1.0.0-SNAPSHOT.jar",
          "url": "waltid-mdoc-credentials2-jvm-1.0.0-SNAPSHOT.jar",
          "size": 490310,
          "sha512": "ba0e52cb1f965b36885d8aa80efe68c9152b2923ee176960a139bb45c3af8182072ed5b0f225074857c7d8c780db1549bd233314e98a27f2e9c9c9d33ddfc5b8",
          "sha256": "5ab0b39f39b8f409243e5aa7741b03e4eef41968e959ab9b0bc66b3431b0ee07",
          "sha1": "afd41f5ad8ba402787f6a509fba3c32acd1dddb4",
          "md5": "69fda835fa8e427d11570b26bf2bca6a"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "waltid-mdoc-credentials2-jvm-1.0.0-SNAPSHOT-sources.jar",
          "url": "waltid-mdoc-credentials2-jvm-1.0.0-SNAPSHOT-sources.jar",
          "size": 77240,
          "sha512": "4cccf927eed815738079cb51791412a6fcf174eedcb4a309fd6866049349b8f9bceb817dda4f4ea09b44c78a920e1e1ac987ac6dc5f375c8631b56f81d3192cf",
          "sha256": "dced2c6f359152bda3f18f7ad16560d8b37701a7bc3d83541627f58894983d93",
          "sha1": "114fdbb64f5ff7334658c3ebaa2124e935898b9d",
          "md5": "462bc629e45dd9e7cc082edb777cb0b7"
        }
      ]
    }
  ]
}
