{
  "formatVersion": "1.1",
  "component": {
    "url": "../../waltid-mdoc-credentials2/1.0.0-SNAPSHOT/waltid-mdoc-credentials2-1.0.0-SNAPSHOT.module",
    "group": "id.walt.credentials",
    "module": "waltid-mdoc-credentials2",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "id.walt.crypto",
          "module": "waltid-cose",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "waltid-mdoc-credentials2-jvm-1.0.0-SNAPSHOT.jar",
          "url": "waltid-mdoc-credentials2-jvm-1.0.0-SNAPSHOT.jar",
          "size": 479784,
          "sha512": "02e129c62679c846a7709c0029a71b88ec9bf55f4af5a984b24508a46df305d51e2d6dc93ef349fcb398bcaf7aa01579914ca06464aaadd21003cfcfa3e3bb13",
          "sha256": "0c16e3f907a7dee4d770306d23210de2c8d86b610f8bd4c95bae7d88c3746838",
          "sha1": "e461ff6ae82c1f912f9f7f90456f8b81f111997d",
          "md5": "8dcdca71e4a93d0e37ed691678649dcc"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "id.walt.crypto",
          "module": "waltid-cose",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.13"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "app.softwork",
          "module": "kotlinx-uuid-core",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.eygraber",
          "module": "jsonpathkt-kotlinx",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-cbor",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "net.orandja.obor",
          "module": "obor",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "org.kotlincrypto.random",
          "module": "crypto-rand",
          "version": {
            "requires": "0.5.2"
          }
        },
        {
          "group": "org.kotlincrypto.hash",
          "module": "bom",
          "version": {
            "requires": "0.7.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.kotlincrypto.hash",
          "module": "sha2"
        },
        {
          "group": "org.kotlincrypto.macs",
          "module": "bom",
          "version": {
            "requires": "0.7.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.kotlincrypto.macs",
          "module": "hmac-sha2"
        },
        {
          "group": "id.walt.crypto",
          "module": "waltid-crypto",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "waltid-mdoc-credentials2-jvm-1.0.0-SNAPSHOT.jar",
          "url": "waltid-mdoc-credentials2-jvm-1.0.0-SNAPSHOT.jar",
          "size": 479784,
          "sha512": "02e129c62679c846a7709c0029a71b88ec9bf55f4af5a984b24508a46df305d51e2d6dc93ef349fcb398bcaf7aa01579914ca06464aaadd21003cfcfa3e3bb13",
          "sha256": "0c16e3f907a7dee4d770306d23210de2c8d86b610f8bd4c95bae7d88c3746838",
          "sha1": "e461ff6ae82c1f912f9f7f90456f8b81f111997d",
          "md5": "8dcdca71e4a93d0e37ed691678649dcc"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "waltid-mdoc-credentials2-jvm-1.0.0-SNAPSHOT-sources.jar",
          "url": "waltid-mdoc-credentials2-jvm-1.0.0-SNAPSHOT-sources.jar",
          "size": 76055,
          "sha512": "2d8ec12756911f06b39c30cf39bef063f8d28a4e6862cea9558d2173b72ae8af87014b3dc5ddddf4914b9585617372d81585aea937234620d905bfb4f19301ac",
          "sha256": "75604db9e1f1cf824d0e262b78b99138e9fa85f094ba3907fab433ef9d47fcff",
          "sha1": "2f2c06ee0d43fd204eecf4bf555c27b92f31349e",
          "md5": "3634f247d416d960b7bd353c346ba920"
        }
      ]
    }
  ]
}
