{
  "formatVersion": "1.1",
  "component": {
    "group": "id.walt.dif-definitions-parser",
    "module": "waltid-dif-definitions-parser",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.eygraber",
          "module": "jsonpathkt-kotlinx",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.optimumcode",
          "module": "json-schema-validator",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "id.walt.credentials",
          "module": "waltid-w3c-credentials",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "waltid-dif-definitions-parser-1.0.0-SNAPSHOT.jar",
          "url": "waltid-dif-definitions-parser-1.0.0-SNAPSHOT.jar",
          "size": 7591,
          "sha512": "b81a9b76f9f4c041ed7e47d416d26d0e4b0e35edfd7693b080d6a3f739114cf48b0416b4984e6a10fbfe2cf66194b6c9c5f323a57f00a255d28e6618aabc0898",
          "sha256": "82e3642ef92b55ed5e3f169bbf353d76f56356cef7bf9ffde1f6babe4eb3bfdd",
          "sha1": "92053a0f4de1f6fe8d619d96aff094759bae0a5a",
          "md5": "c34529f2cb4383cdcfdd5340be699012"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "waltid-dif-definitions-parser-1.0.0-SNAPSHOT-sources.jar",
          "url": "waltid-dif-definitions-parser-1.0.0-SNAPSHOT-sources.jar",
          "size": 4206,
          "sha512": "49fa058c5fb18eeb34b816e74b7b4a18cb8dab3a79e10e356e524e6b2c4d0f9b7f4c561000bbdc4b64cb5d473d9325b20a99cb3d328b7d1f90ea13f861758b45",
          "sha256": "b3f5d4572bda3784eeac814e4f98713ff3ee3ec2270d3cdb4cc7ec9d967c1c22",
          "sha1": "1d46b883513e59219052839392459971b34ef546",
          "md5": "8fe13f379f388725b84dd5c6e79904cf"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../waltid-dif-definitions-parser-iosarm64/1.0.0-SNAPSHOT/waltid-dif-definitions-parser-iosarm64-1.0.0-SNAPSHOT.module",
        "group": "id.walt.dif-definitions-parser",
        "module": "waltid-dif-definitions-parser-iosarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../waltid-dif-definitions-parser-iosarm64/1.0.0-SNAPSHOT/waltid-dif-definitions-parser-iosarm64-1.0.0-SNAPSHOT.module",
        "group": "id.walt.dif-definitions-parser",
        "module": "waltid-dif-definitions-parser-iosarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../waltid-dif-definitions-parser-iosarm64/1.0.0-SNAPSHOT/waltid-dif-definitions-parser-iosarm64-1.0.0-SNAPSHOT.module",
        "group": "id.walt.dif-definitions-parser",
        "module": "waltid-dif-definitions-parser-iosarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../waltid-dif-definitions-parser-iossimulatorarm64/1.0.0-SNAPSHOT/waltid-dif-definitions-parser-iossimulatorarm64-1.0.0-SNAPSHOT.module",
        "group": "id.walt.dif-definitions-parser",
        "module": "waltid-dif-definitions-parser-iossimulatorarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../waltid-dif-definitions-parser-iossimulatorarm64/1.0.0-SNAPSHOT/waltid-dif-definitions-parser-iossimulatorarm64-1.0.0-SNAPSHOT.module",
        "group": "id.walt.dif-definitions-parser",
        "module": "waltid-dif-definitions-parser-iossimulatorarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../waltid-dif-definitions-parser-iossimulatorarm64/1.0.0-SNAPSHOT/waltid-dif-definitions-parser-iossimulatorarm64-1.0.0-SNAPSHOT.module",
        "group": "id.walt.dif-definitions-parser",
        "module": "waltid-dif-definitions-parser-iossimulatorarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../waltid-dif-definitions-parser-js/1.0.0-SNAPSHOT/waltid-dif-definitions-parser-js-1.0.0-SNAPSHOT.module",
        "group": "id.walt.dif-definitions-parser",
        "module": "waltid-dif-definitions-parser-js",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../waltid-dif-definitions-parser-js/1.0.0-SNAPSHOT/waltid-dif-definitions-parser-js-1.0.0-SNAPSHOT.module",
        "group": "id.walt.dif-definitions-parser",
        "module": "waltid-dif-definitions-parser-js",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../waltid-dif-definitions-parser-js/1.0.0-SNAPSHOT/waltid-dif-definitions-parser-js-1.0.0-SNAPSHOT.module",
        "group": "id.walt.dif-definitions-parser",
        "module": "waltid-dif-definitions-parser-js",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../waltid-dif-definitions-parser-jvm/1.0.0-SNAPSHOT/waltid-dif-definitions-parser-jvm-1.0.0-SNAPSHOT.module",
        "group": "id.walt.dif-definitions-parser",
        "module": "waltid-dif-definitions-parser-jvm",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../waltid-dif-definitions-parser-jvm/1.0.0-SNAPSHOT/waltid-dif-definitions-parser-jvm-1.0.0-SNAPSHOT.module",
        "group": "id.walt.dif-definitions-parser",
        "module": "waltid-dif-definitions-parser-jvm",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../waltid-dif-definitions-parser-jvm/1.0.0-SNAPSHOT/waltid-dif-definitions-parser-jvm-1.0.0-SNAPSHOT.module",
        "group": "id.walt.dif-definitions-parser",
        "module": "waltid-dif-definitions-parser-jvm",
        "version": "1.0.0-SNAPSHOT"
      }
    }
  ]
}
