{
  "formatVersion": "1.1",
  "component": {
    "url": "../../waltid-target-ios/1.0.0-SNAPSHOT/waltid-target-ios-1.0.0-SNAPSHOT.module",
    "group": "id.walt.crypto",
    "module": "waltid-target-ios",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "waltid-target-ios-iosArm64Main-1.0.0-SNAPSHOT.klib",
          "url": "waltid-target-ios-iosarm64-1.0.0-SNAPSHOT.klib",
          "size": 78720,
          "sha512": "eadf65e33adc47031adb03f09cf431bd870fab31852357b75d4ee34499ec81b052c731a0c9279467ba8163d78c01b3759eff97191cd102ecffa6bec62f1f6e24",
          "sha256": "1a86697ef845c973386a961b8f15b2b574091aa4a824239787025afcd9a0bc3f",
          "sha1": "6061a2c040fa5f04b807a70481e8263047889432",
          "md5": "ddf897826467c6b222fa8f6fb02764e0"
        },
        {
          "name": "waltid-target-ios-iosArm64Cinterop-implementationMain-1.0.0-SNAPSHOT.klib",
          "url": "waltid-target-ios-iosarm64-1.0.0-SNAPSHOT-cinterop-implementation.klib",
          "size": 116203,
          "sha512": "ee6b162d39cd26e94c88e6b1eacc0c553d3fd1569676ac5a5157d9e0208c3cffe5e8dcd4eef51d7e4170e8ee8c717299ba5efbd16ec4fafd8fe3e210c346eda3",
          "sha256": "25b4b04a7610cd660fbc99621d7732e7805c7a89ce4d7ad013bb16e8f382c2dd",
          "sha1": "1350fb25e48860117db424c2512054e15ae68203",
          "md5": "f3b14bda788e5aeb9180b2e204423e57"
        },
        {
          "name": "waltid-target-ios-iosArm64Cinterop-JOSESwiftMain-1.0.0-SNAPSHOT.klib",
          "url": "waltid-target-ios-iosarm64-1.0.0-SNAPSHOT-cinterop-JOSESwift.klib",
          "size": 6834,
          "sha512": "bd298cc5404e839447a07abb80b241f999706685fcde7f7d4297f69b2f890a5db056d8d18b3adbdf32827169a70123c43cb683c87dffaf9a0a75471442313b5f",
          "sha256": "bef3bb6e3a7a39674418b048eb8888937ac2dca264b9d2d402e0f7fa25a0d11d",
          "sha1": "19e0a30f7a1454f98eed8f18362e421c8bfab516",
          "md5": "d7a352274db015a6c99a167b179bf521"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "waltid-target-ios-iosarm64-1.0.0-SNAPSHOT-sources.jar",
          "url": "waltid-target-ios-iosarm64-1.0.0-SNAPSHOT-sources.jar",
          "size": 11219,
          "sha512": "9957db3009465970cf608796ef4460d5c9a8e36336c89ff5d1d76c7833b794cefc6f89c47afe2d6150bc9c38c1a13bef8b68bfcebfbf94d65907007b4be9aff5",
          "sha256": "db20969e183baa46478e719313c139b8d90e46acacdf306971a67d6e1a834e64",
          "sha1": "d728d6d78e47eb5dc5f09a63b40aee82e2992b27",
          "md5": "613c876386f383d96f85461e4fb498c2"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "waltid-target-ios-iosarm64-1.0.0-SNAPSHOT-metadata.jar",
          "url": "waltid-target-ios-iosarm64-1.0.0-SNAPSHOT-metadata.jar",
          "size": 38342,
          "sha512": "145d8f7c8909a3fc7b84fd9d01ed4adb4a3c70fa4b896f53a76c52ea9508af44058f77f820a0964acc20c2e27680fa1913ead05da0f6960ed1f926b9791bddbe",
          "sha256": "29c01b56d77807de2af4f97f8f431bbccbf4d90dc310b0153946c0039b82308d",
          "sha1": "d81258762e690aa8a9a77f1155fd927ee232936b",
          "md5": "7bfa4e9a10f4cbaf9eada312e186737b"
        }
      ]
    }
  ]
}
