{
  "formatVersion": "1.1",
  "component": {
    "group": "id.walt.mdoc-credentials",
    "module": "waltid-mdoc-credentials",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.soywiz.korlibs.krypto",
          "module": "krypto",
          "version": {
            "requires": "4.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "waltid-mdoc-credentials-1.0.0-SNAPSHOT.jar",
          "url": "waltid-mdoc-credentials-1.0.0-SNAPSHOT.jar",
          "size": 68377,
          "sha512": "e0e9241a930f7a1913ce78cd6e5b96a0950f4e45e2d746de1f6d7b1d85b70fc17fe752b1e40ff0f51bd46478641ca39aac2d735825e54ce2a624c2e5b6497586",
          "sha256": "70cafd940be59152eefc7d68a706d7903ffc53b86ee48cc138ff3252099dfe35",
          "sha1": "29695665980ca78f5a92af27219561412bd96943",
          "md5": "7228abfc3152f83cd2760d3e0d277d19"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "waltid-mdoc-credentials-1.0.0-SNAPSHOT-sources.jar",
          "url": "waltid-mdoc-credentials-1.0.0-SNAPSHOT-sources.jar",
          "size": 78133,
          "sha512": "fba54f87690c655d1a987561e2705ad5c1bd7a3b1f21f5c42366bb978acfd8dc8312852a06d2d0ba829b57fb0d1753bdb317a144de96b02112aba571d23f4af2",
          "sha256": "250b7c050d0a9f663e1a60aa5997ee9a3536d397da7c4a0863db0bd38d5c0217",
          "sha1": "a9e332e08da17664c8d14fbf17dc542d635761d7",
          "md5": "95268b64d2f8e13b105d41700a602bfe"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../waltid-mdoc-credentials-iosarm64/1.0.0-SNAPSHOT/waltid-mdoc-credentials-iosarm64-1.0.0-SNAPSHOT.module",
        "group": "id.walt.mdoc-credentials",
        "module": "waltid-mdoc-credentials-iosarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../waltid-mdoc-credentials-iosarm64/1.0.0-SNAPSHOT/waltid-mdoc-credentials-iosarm64-1.0.0-SNAPSHOT.module",
        "group": "id.walt.mdoc-credentials",
        "module": "waltid-mdoc-credentials-iosarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../waltid-mdoc-credentials-iosarm64/1.0.0-SNAPSHOT/waltid-mdoc-credentials-iosarm64-1.0.0-SNAPSHOT.module",
        "group": "id.walt.mdoc-credentials",
        "module": "waltid-mdoc-credentials-iosarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../waltid-mdoc-credentials-iossimulatorarm64/1.0.0-SNAPSHOT/waltid-mdoc-credentials-iossimulatorarm64-1.0.0-SNAPSHOT.module",
        "group": "id.walt.mdoc-credentials",
        "module": "waltid-mdoc-credentials-iossimulatorarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../waltid-mdoc-credentials-iossimulatorarm64/1.0.0-SNAPSHOT/waltid-mdoc-credentials-iossimulatorarm64-1.0.0-SNAPSHOT.module",
        "group": "id.walt.mdoc-credentials",
        "module": "waltid-mdoc-credentials-iossimulatorarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../waltid-mdoc-credentials-iossimulatorarm64/1.0.0-SNAPSHOT/waltid-mdoc-credentials-iossimulatorarm64-1.0.0-SNAPSHOT.module",
        "group": "id.walt.mdoc-credentials",
        "module": "waltid-mdoc-credentials-iossimulatorarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../waltid-mdoc-credentials-js/1.0.0-SNAPSHOT/waltid-mdoc-credentials-js-1.0.0-SNAPSHOT.module",
        "group": "id.walt.mdoc-credentials",
        "module": "waltid-mdoc-credentials-js",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../waltid-mdoc-credentials-js/1.0.0-SNAPSHOT/waltid-mdoc-credentials-js-1.0.0-SNAPSHOT.module",
        "group": "id.walt.mdoc-credentials",
        "module": "waltid-mdoc-credentials-js",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../waltid-mdoc-credentials-js/1.0.0-SNAPSHOT/waltid-mdoc-credentials-js-1.0.0-SNAPSHOT.module",
        "group": "id.walt.mdoc-credentials",
        "module": "waltid-mdoc-credentials-js",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../waltid-mdoc-credentials-jvm/1.0.0-SNAPSHOT/waltid-mdoc-credentials-jvm-1.0.0-SNAPSHOT.module",
        "group": "id.walt.mdoc-credentials",
        "module": "waltid-mdoc-credentials-jvm",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../waltid-mdoc-credentials-jvm/1.0.0-SNAPSHOT/waltid-mdoc-credentials-jvm-1.0.0-SNAPSHOT.module",
        "group": "id.walt.mdoc-credentials",
        "module": "waltid-mdoc-credentials-jvm",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../waltid-mdoc-credentials-jvm/1.0.0-SNAPSHOT/waltid-mdoc-credentials-jvm-1.0.0-SNAPSHOT.module",
        "group": "id.walt.mdoc-credentials",
        "module": "waltid-mdoc-credentials-jvm",
        "version": "1.0.0-SNAPSHOT"
      }
    }
  ]
}
