{
  "formatVersion": "1.1",
  "component": {
    "url": "../../waltid-w3c-credentials/1.0.0-SNAPSHOT/waltid-w3c-credentials-1.0.0-SNAPSHOT.module",
    "group": "id.walt.credentials",
    "module": "waltid-w3c-credentials",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "id.walt.crypto",
          "module": "waltid-crypto",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "id.walt.sdjwt",
          "module": "waltid-sdjwt",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "id.walt.did",
          "module": "waltid-did",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "waltid-w3c-credentials-jvm-1.0.0-SNAPSHOT.jar",
          "url": "waltid-w3c-credentials-jvm-1.0.0-SNAPSHOT.jar",
          "size": 251944,
          "sha512": "aa31de24ff7f9015485cf423d2592057c81efed36a89ce0ed4679803ab88412696f5412746216e5899360b5eba73e0ceee07adb3180211be21c7664402206194",
          "sha256": "4a5872b3f9ac2f04c19e5b054297ea64a2afcbbf33b4d8d2f164d3bc0375b66e",
          "sha1": "46b34538953cc0d1986d0dcf3c23120be76e55a2",
          "md5": "eacf68543fa41b2b209b32ffdc0813fd"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "id.walt.crypto",
          "module": "waltid-crypto",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "id.walt.sdjwt",
          "module": "waltid-sdjwt",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "id.walt.did",
          "module": "waltid-did",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.github.erdtman",
          "module": "java-json-canonicalization",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "love.forte.plugin.suspend-transform",
          "module": "suspend-transform-runtime-jvm",
          "version": {
            "requires": "2.2.20-0.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.github.optimumcode",
          "module": "json-schema-validator",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "app.softwork",
          "module": "kotlinx-uuid-core",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.5"
          }
        },
        {
          "group": "love.forte.plugin.suspend-transform",
          "module": "suspend-transform-annotation",
          "version": {
            "requires": "2.2.20-0.13.1"
          }
        },
        {
          "group": "love.forte.plugin.suspend-transform",
          "module": "suspend-transform-runtime",
          "version": {
            "requires": "2.2.20-0.13.1"
          }
        }
      ],
      "files": [
        {
          "name": "waltid-w3c-credentials-jvm-1.0.0-SNAPSHOT.jar",
          "url": "waltid-w3c-credentials-jvm-1.0.0-SNAPSHOT.jar",
          "size": 251944,
          "sha512": "aa31de24ff7f9015485cf423d2592057c81efed36a89ce0ed4679803ab88412696f5412746216e5899360b5eba73e0ceee07adb3180211be21c7664402206194",
          "sha256": "4a5872b3f9ac2f04c19e5b054297ea64a2afcbbf33b4d8d2f164d3bc0375b66e",
          "sha1": "46b34538953cc0d1986d0dcf3c23120be76e55a2",
          "md5": "eacf68543fa41b2b209b32ffdc0813fd"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "waltid-w3c-credentials-jvm-1.0.0-SNAPSHOT-sources.jar",
          "url": "waltid-w3c-credentials-jvm-1.0.0-SNAPSHOT-sources.jar",
          "size": 18069,
          "sha512": "c3c773e87940d32e12c6f385a4c7baf945cad8ebaf360aaae8d239b6892cd135d59bb894722b330bebfc5c48a61615e7c41c500165f7bc5d5a7d211d292dfdef",
          "sha256": "44830bb02aef67264cc68e258312ac878e1bc104e47eac33cb6c9205984d8372",
          "sha1": "81e8150b14f8741b7c26290a2a566949f9fbea23",
          "md5": "c9e844347e2dff61fa12f9b4b4254fd9"
        }
      ]
    }
  ]
}
