{
  "formatVersion": "1.1",
  "component": {
    "url": "../../waltid-mdoc-credentials/1.0.0-SNAPSHOT/waltid-mdoc-credentials-1.0.0-SNAPSHOT.module",
    "group": "id.walt.mdoc-credentials",
    "module": "waltid-mdoc-credentials",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "waltid-mdoc-credentials-jvm-1.0.0-SNAPSHOT.jar",
          "url": "waltid-mdoc-credentials-jvm-1.0.0-SNAPSHOT.jar",
          "size": 465461,
          "sha512": "788d24fcfda9626b532ab5a5a28998abef88d2bb30781b8a8a091b6a2d63c5c21d5bd400ebe063ffd6fc96689ddd55c991babbfdc4e90c0a0fcff6f55580a806",
          "sha256": "edb140900c5ee45bc042235649c584274feeb4102e11ed072079ac93fb997e13",
          "sha1": "3a2b81db268f1aa184da5e2bf923e6983b5036b9",
          "md5": "a7479fc85c08eee0f4467e90dd419a86"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.cose",
          "module": "cose-java",
          "version": {
            "requires": "1.1.1-WALT-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.soywiz.korlibs.krypto",
          "module": "krypto",
          "version": {
            "requires": "4.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "waltid-mdoc-credentials-jvm-1.0.0-SNAPSHOT.jar",
          "url": "waltid-mdoc-credentials-jvm-1.0.0-SNAPSHOT.jar",
          "size": 465461,
          "sha512": "788d24fcfda9626b532ab5a5a28998abef88d2bb30781b8a8a091b6a2d63c5c21d5bd400ebe063ffd6fc96689ddd55c991babbfdc4e90c0a0fcff6f55580a806",
          "sha256": "edb140900c5ee45bc042235649c584274feeb4102e11ed072079ac93fb997e13",
          "sha1": "3a2b81db268f1aa184da5e2bf923e6983b5036b9",
          "md5": "a7479fc85c08eee0f4467e90dd419a86"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "waltid-mdoc-credentials-jvm-1.0.0-SNAPSHOT-sources.jar",
          "url": "waltid-mdoc-credentials-jvm-1.0.0-SNAPSHOT-sources.jar",
          "size": 80992,
          "sha512": "04029bd4302a36cd66db5c7cbf36c2058d0109c9eaef03df2ce3a3bafdffbcf6839618e4e5eaedfa33a12659928c9731d3833c8c722036e769710aa98e19eda2",
          "sha256": "0da948e4afb1ce8115f60bdde9f0c29cc62029b2bc569068f41b231477043a2c",
          "sha1": "651b9c2f6065cc3724308a622ed1985a53d9177f",
          "md5": "bbcea0661aa192e02d90b18e0ed3849f"
        }
      ]
    }
  ]
}
