{
  "formatVersion": "1.1",
  "component": {
    "url": "../../waltid-crypto/1.0.0-SNAPSHOT/waltid-crypto-1.0.0-SNAPSHOT.module",
    "group": "id.walt.crypto",
    "module": "waltid-crypto",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "waltid-crypto-jvm-1.0.0-SNAPSHOT.jar",
          "url": "waltid-crypto-jvm-1.0.0-SNAPSHOT.jar",
          "size": 857707,
          "sha512": "99eb902a1e110d3fe1d91785975bfdbc750b8c8b18aa9b992ac0d510e8f45b83894bcd03660d40fa683202b0146670512f230ffc1972a1fa88f246f983ac967d",
          "sha256": "191309f92253f96237306a0047f814206cf6a6d62bba9cd00b28f5edd8b8c10a",
          "sha1": "9a096e7258a5016828a1e64a4d7ac319e6226b9d",
          "md5": "23364799df106bc529fac0f256ce41c3"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.google.crypto.tink",
          "module": "tink",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-lts8on",
          "version": {
            "requires": "2.73.8"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-lts8on",
          "version": {
            "requires": "2.73.8"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.nimbusds",
          "module": "nimbus-jose-jwt",
          "version": {
            "requires": "10.0.1"
          }
        },
        {
          "group": "love.forte.plugin.suspend-transform",
          "module": "suspend-transform-runtime-jvm",
          "version": {
            "requires": "2.2.20-0.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.kotlincrypto.hash",
          "module": "bom",
          "version": {
            "requires": "0.6.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.kotlincrypto.hash",
          "module": "sha2"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.github.reactivecircus.cache4k",
          "module": "cache4k",
          "version": {
            "requires": "0.14.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.5"
          }
        },
        {
          "group": "love.forte.plugin.suspend-transform",
          "module": "suspend-transform-annotation",
          "version": {
            "requires": "2.2.20-0.13.1"
          }
        },
        {
          "group": "org.kotlincrypto.macs",
          "module": "bom",
          "version": {
            "requires": "0.6.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.kotlincrypto.macs",
          "module": "hmac-sha2"
        },
        {
          "group": "love.forte.plugin.suspend-transform",
          "module": "suspend-transform-runtime",
          "version": {
            "requires": "2.2.20-0.13.1"
          }
        }
      ],
      "files": [
        {
          "name": "waltid-crypto-jvm-1.0.0-SNAPSHOT.jar",
          "url": "waltid-crypto-jvm-1.0.0-SNAPSHOT.jar",
          "size": 857707,
          "sha512": "99eb902a1e110d3fe1d91785975bfdbc750b8c8b18aa9b992ac0d510e8f45b83894bcd03660d40fa683202b0146670512f230ffc1972a1fa88f246f983ac967d",
          "sha256": "191309f92253f96237306a0047f814206cf6a6d62bba9cd00b28f5edd8b8c10a",
          "sha1": "9a096e7258a5016828a1e64a4d7ac319e6226b9d",
          "md5": "23364799df106bc529fac0f256ce41c3"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "waltid-crypto-jvm-1.0.0-SNAPSHOT-sources.jar",
          "url": "waltid-crypto-jvm-1.0.0-SNAPSHOT-sources.jar",
          "size": 63152,
          "sha512": "09d59489bcee17b4ff4c66527f47b36dccd65afa2f5a8220475f68f07baa9108a4078754bdedbe1c30a14a0284f380ece72e6ed69b5b04bf90a079a79ed5eae2",
          "sha256": "8f24e79c93211fdba9e3fb3e2809c0d8293a833c95237230e8a8b1a9747842ec",
          "sha1": "43507ae9b99f0da5bafb047d7b4879cd4a03806f",
          "md5": "c573db24b365c22bf3af2d290bf16f6f"
        }
      ]
    }
  ]
}
