{
  "formatVersion": "1.1",
  "component": {
    "url": "../../waltid-crypto/1.0.0-SNAPSHOT/waltid-crypto-1.0.0-SNAPSHOT.module",
    "group": "id.walt.crypto",
    "module": "waltid-crypto",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "waltid-crypto-jvm-1.0.0-SNAPSHOT.jar",
          "url": "waltid-crypto-jvm-1.0.0-SNAPSHOT.jar",
          "size": 851202,
          "sha512": "8c2c8e05afa85bda9b21171887be4973e28f7362f697a21df2a1fb5f8fbc73f221f3c2fa56a2b01c6376a5cfac497142d05a94903747de53c4a79b6605657d4c",
          "sha256": "3e924636f0aef9547ad9176f001f034784a3558d74618cfb2af16a0e8e74ebcc",
          "sha1": "2ee2fa26b99b28f83d4a9106248475cbf658e3d8",
          "md5": "42ccaf20f99b55f43a8d32b3bb9d06c5"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "com.google.crypto.tink",
          "module": "tink",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-lts8on",
          "version": {
            "requires": "2.73.8"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-lts8on",
          "version": {
            "requires": "2.73.8"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.nimbusds",
          "module": "nimbus-jose-jwt",
          "version": {
            "requires": "10.0.1"
          }
        },
        {
          "group": "love.forte.plugin.suspend-transform",
          "module": "suspend-transform-runtime-jvm",
          "version": {
            "requires": "2.2.20-0.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.kotlincrypto.hash",
          "module": "bom",
          "version": {
            "requires": "0.6.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.kotlincrypto.hash",
          "module": "sha2"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.github.reactivecircus.cache4k",
          "module": "cache4k",
          "version": {
            "requires": "0.14.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.5"
          }
        },
        {
          "group": "love.forte.plugin.suspend-transform",
          "module": "suspend-transform-annotation",
          "version": {
            "requires": "2.2.20-0.13.1"
          }
        },
        {
          "group": "org.kotlincrypto.macs",
          "module": "bom",
          "version": {
            "requires": "0.6.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.kotlincrypto.macs",
          "module": "hmac-sha2"
        },
        {
          "group": "love.forte.plugin.suspend-transform",
          "module": "suspend-transform-runtime",
          "version": {
            "requires": "2.2.20-0.13.1"
          }
        }
      ],
      "files": [
        {
          "name": "waltid-crypto-jvm-1.0.0-SNAPSHOT.jar",
          "url": "waltid-crypto-jvm-1.0.0-SNAPSHOT.jar",
          "size": 851202,
          "sha512": "8c2c8e05afa85bda9b21171887be4973e28f7362f697a21df2a1fb5f8fbc73f221f3c2fa56a2b01c6376a5cfac497142d05a94903747de53c4a79b6605657d4c",
          "sha256": "3e924636f0aef9547ad9176f001f034784a3558d74618cfb2af16a0e8e74ebcc",
          "sha1": "2ee2fa26b99b28f83d4a9106248475cbf658e3d8",
          "md5": "42ccaf20f99b55f43a8d32b3bb9d06c5"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "waltid-crypto-jvm-1.0.0-SNAPSHOT-sources.jar",
          "url": "waltid-crypto-jvm-1.0.0-SNAPSHOT-sources.jar",
          "size": 62934,
          "sha512": "d0f2727a24a4132e67eff90c6645d3aca5baa00b2548789bddc52a021f793ecc9acf6c2750eed3d86ec6cb496e92611ef4518b123425efc8f30fe13f4ba47112",
          "sha256": "055d8e0c8ae17c693f4dfacd078140a601a3cba3bc93fcf850a5b4ea516521da",
          "sha1": "ceacdb51ed053b8b78ed4c4e2378ee3cb05ac87f",
          "md5": "4d3864a5bb79bddd1f9c2378f9cd15e9"
        }
      ]
    }
  ]
}
