{
  "formatVersion": "1.1",
  "component": {
    "url": "../../waltid-mdoc-credentials/1.0.0-SNAPSHOT/waltid-mdoc-credentials-1.0.0-SNAPSHOT.module",
    "group": "id.walt.mdoc-credentials",
    "module": "waltid-mdoc-credentials",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.soywiz.korlibs.krypto",
          "module": "krypto",
          "version": {
            "requires": "4.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "waltid-mdoc-credentials-iosSimulatorArm64Main-1.0.0-SNAPSHOT.klib",
          "url": "waltid-mdoc-credentials-iossimulatorarm64-1.0.0-SNAPSHOT.klib",
          "size": 413789,
          "sha512": "cb4f853c3996ab264f3512628b6dc0b0c6f6d5a077652bd3251420345e1c3c4a126c39cbdd1606f82cb7860fbcd190617284579a4ca6d19e3753283ac198529b",
          "sha256": "352617b9e57f6d37523168f19a7dfd4337a5332524f9a977fa78595781a1a24b",
          "sha1": "6d648d829f86844faa24c93783eba3e39738b7e9",
          "md5": "111e679d8ba7f58f9e519dd06bb34442"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "waltid-mdoc-credentials-iossimulatorarm64-1.0.0-SNAPSHOT-sources.jar",
          "url": "waltid-mdoc-credentials-iossimulatorarm64-1.0.0-SNAPSHOT-sources.jar",
          "size": 78133,
          "sha512": "fba54f87690c655d1a987561e2705ad5c1bd7a3b1f21f5c42366bb978acfd8dc8312852a06d2d0ba829b57fb0d1753bdb317a144de96b02112aba571d23f4af2",
          "sha256": "250b7c050d0a9f663e1a60aa5997ee9a3536d397da7c4a0863db0bd38d5c0217",
          "sha1": "a9e332e08da17664c8d14fbf17dc542d635761d7",
          "md5": "95268b64d2f8e13b105d41700a602bfe"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.soywiz.korlibs.krypto",
          "module": "krypto",
          "version": {
            "requires": "4.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "waltid-mdoc-credentials-iossimulatorarm64-1.0.0-SNAPSHOT-metadata.jar",
          "url": "waltid-mdoc-credentials-iossimulatorarm64-1.0.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
