{
  "formatVersion": "1.1",
  "component": {
    "group": "id.walt.credentials",
    "module": "waltid-mdoc-credentials2",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "id.walt.crypto",
          "module": "waltid-cose",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "waltid-mdoc-credentials2-1.0.0-SNAPSHOT.jar",
          "url": "waltid-mdoc-credentials2-1.0.0-SNAPSHOT.jar",
          "size": 62363,
          "sha512": "f3dac34db5dadc282e90f0d8a9050e6dd6c55b13e0f5d1658ce9c3080de7858df5264dac1db5d77f4c7600acd3e1a554c5e9dc7dd37afe7d33111b2cd8591aa6",
          "sha256": "b98cb056eaa0ecabb28b258f9c0b62e7af7384c6771a6dc55e03d7d6f36a61d8",
          "sha1": "9d9d1e0c66445ced314fd80c92267abc98070d7f",
          "md5": "bcb82320bc418b25cb085ac5efceae76"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "waltid-mdoc-credentials2-1.0.0-SNAPSHOT-sources.jar",
          "url": "waltid-mdoc-credentials2-1.0.0-SNAPSHOT-sources.jar",
          "size": 77240,
          "sha512": "4cccf927eed815738079cb51791412a6fcf174eedcb4a309fd6866049349b8f9bceb817dda4f4ea09b44c78a920e1e1ac987ac6dc5f375c8631b56f81d3192cf",
          "sha256": "dced2c6f359152bda3f18f7ad16560d8b37701a7bc3d83541627f58894983d93",
          "sha1": "114fdbb64f5ff7334658c3ebaa2124e935898b9d",
          "md5": "462bc629e45dd9e7cc082edb777cb0b7"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../waltid-mdoc-credentials2-iosarm64/1.0.0-SNAPSHOT/waltid-mdoc-credentials2-iosarm64-1.0.0-SNAPSHOT.module",
        "group": "id.walt.credentials",
        "module": "waltid-mdoc-credentials2-iosarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../waltid-mdoc-credentials2-iosarm64/1.0.0-SNAPSHOT/waltid-mdoc-credentials2-iosarm64-1.0.0-SNAPSHOT.module",
        "group": "id.walt.credentials",
        "module": "waltid-mdoc-credentials2-iosarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../waltid-mdoc-credentials2-iosarm64/1.0.0-SNAPSHOT/waltid-mdoc-credentials2-iosarm64-1.0.0-SNAPSHOT.module",
        "group": "id.walt.credentials",
        "module": "waltid-mdoc-credentials2-iosarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../waltid-mdoc-credentials2-iossimulatorarm64/1.0.0-SNAPSHOT/waltid-mdoc-credentials2-iossimulatorarm64-1.0.0-SNAPSHOT.module",
        "group": "id.walt.credentials",
        "module": "waltid-mdoc-credentials2-iossimulatorarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../waltid-mdoc-credentials2-iossimulatorarm64/1.0.0-SNAPSHOT/waltid-mdoc-credentials2-iossimulatorarm64-1.0.0-SNAPSHOT.module",
        "group": "id.walt.credentials",
        "module": "waltid-mdoc-credentials2-iossimulatorarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../waltid-mdoc-credentials2-iossimulatorarm64/1.0.0-SNAPSHOT/waltid-mdoc-credentials2-iossimulatorarm64-1.0.0-SNAPSHOT.module",
        "group": "id.walt.credentials",
        "module": "waltid-mdoc-credentials2-iossimulatorarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../waltid-mdoc-credentials2-js/1.0.0-SNAPSHOT/waltid-mdoc-credentials2-js-1.0.0-SNAPSHOT.module",
        "group": "id.walt.credentials",
        "module": "waltid-mdoc-credentials2-js",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../waltid-mdoc-credentials2-js/1.0.0-SNAPSHOT/waltid-mdoc-credentials2-js-1.0.0-SNAPSHOT.module",
        "group": "id.walt.credentials",
        "module": "waltid-mdoc-credentials2-js",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../waltid-mdoc-credentials2-js/1.0.0-SNAPSHOT/waltid-mdoc-credentials2-js-1.0.0-SNAPSHOT.module",
        "group": "id.walt.credentials",
        "module": "waltid-mdoc-credentials2-js",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../waltid-mdoc-credentials2-jvm/1.0.0-SNAPSHOT/waltid-mdoc-credentials2-jvm-1.0.0-SNAPSHOT.module",
        "group": "id.walt.credentials",
        "module": "waltid-mdoc-credentials2-jvm",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../waltid-mdoc-credentials2-jvm/1.0.0-SNAPSHOT/waltid-mdoc-credentials2-jvm-1.0.0-SNAPSHOT.module",
        "group": "id.walt.credentials",
        "module": "waltid-mdoc-credentials2-jvm",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../waltid-mdoc-credentials2-jvm/1.0.0-SNAPSHOT/waltid-mdoc-credentials2-jvm-1.0.0-SNAPSHOT.module",
        "group": "id.walt.credentials",
        "module": "waltid-mdoc-credentials2-jvm",
        "version": "1.0.0-SNAPSHOT"
      }
    }
  ]
}
