{
  "formatVersion": "1.1",
  "component": {
    "group": "id.walt.credentials",
    "module": "waltid-mdoc-credentials2",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "id.walt.crypto",
          "module": "waltid-cose",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "waltid-mdoc-credentials2-1.0.0-SNAPSHOT.jar",
          "url": "waltid-mdoc-credentials2-1.0.0-SNAPSHOT.jar",
          "size": 61987,
          "sha512": "279b178b4b3087a845e5c7f14f631d77733d24aba3272665f78e406726385d595f710a3cebbbc08ea47a6e18b4165ae76444908cc24aa56b8cdf2c316fc86107",
          "sha256": "fe7aeb4b4234f6ef64dcc0d4f05946c757c49c0c7e80083de2feb1a5d3db2773",
          "sha1": "7f71c17d2c5c5828e7926519eabae2ed964d7ccf",
          "md5": "3abc097e425864f5d67f505570e00711"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "waltid-mdoc-credentials2-1.0.0-SNAPSHOT-sources.jar",
          "url": "waltid-mdoc-credentials2-1.0.0-SNAPSHOT-sources.jar",
          "size": 76055,
          "sha512": "2d8ec12756911f06b39c30cf39bef063f8d28a4e6862cea9558d2173b72ae8af87014b3dc5ddddf4914b9585617372d81585aea937234620d905bfb4f19301ac",
          "sha256": "75604db9e1f1cf824d0e262b78b99138e9fa85f094ba3907fab433ef9d47fcff",
          "sha1": "2f2c06ee0d43fd204eecf4bf555c27b92f31349e",
          "md5": "3634f247d416d960b7bd353c346ba920"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../waltid-mdoc-credentials2-iosarm64/1.0.0-SNAPSHOT/waltid-mdoc-credentials2-iosarm64-1.0.0-SNAPSHOT.module",
        "group": "id.walt.credentials",
        "module": "waltid-mdoc-credentials2-iosarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../waltid-mdoc-credentials2-iosarm64/1.0.0-SNAPSHOT/waltid-mdoc-credentials2-iosarm64-1.0.0-SNAPSHOT.module",
        "group": "id.walt.credentials",
        "module": "waltid-mdoc-credentials2-iosarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../waltid-mdoc-credentials2-iosarm64/1.0.0-SNAPSHOT/waltid-mdoc-credentials2-iosarm64-1.0.0-SNAPSHOT.module",
        "group": "id.walt.credentials",
        "module": "waltid-mdoc-credentials2-iosarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../waltid-mdoc-credentials2-iossimulatorarm64/1.0.0-SNAPSHOT/waltid-mdoc-credentials2-iossimulatorarm64-1.0.0-SNAPSHOT.module",
        "group": "id.walt.credentials",
        "module": "waltid-mdoc-credentials2-iossimulatorarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../waltid-mdoc-credentials2-iossimulatorarm64/1.0.0-SNAPSHOT/waltid-mdoc-credentials2-iossimulatorarm64-1.0.0-SNAPSHOT.module",
        "group": "id.walt.credentials",
        "module": "waltid-mdoc-credentials2-iossimulatorarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../waltid-mdoc-credentials2-iossimulatorarm64/1.0.0-SNAPSHOT/waltid-mdoc-credentials2-iossimulatorarm64-1.0.0-SNAPSHOT.module",
        "group": "id.walt.credentials",
        "module": "waltid-mdoc-credentials2-iossimulatorarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../waltid-mdoc-credentials2-js/1.0.0-SNAPSHOT/waltid-mdoc-credentials2-js-1.0.0-SNAPSHOT.module",
        "group": "id.walt.credentials",
        "module": "waltid-mdoc-credentials2-js",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../waltid-mdoc-credentials2-js/1.0.0-SNAPSHOT/waltid-mdoc-credentials2-js-1.0.0-SNAPSHOT.module",
        "group": "id.walt.credentials",
        "module": "waltid-mdoc-credentials2-js",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../waltid-mdoc-credentials2-js/1.0.0-SNAPSHOT/waltid-mdoc-credentials2-js-1.0.0-SNAPSHOT.module",
        "group": "id.walt.credentials",
        "module": "waltid-mdoc-credentials2-js",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../waltid-mdoc-credentials2-jvm/1.0.0-SNAPSHOT/waltid-mdoc-credentials2-jvm-1.0.0-SNAPSHOT.module",
        "group": "id.walt.credentials",
        "module": "waltid-mdoc-credentials2-jvm",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../waltid-mdoc-credentials2-jvm/1.0.0-SNAPSHOT/waltid-mdoc-credentials2-jvm-1.0.0-SNAPSHOT.module",
        "group": "id.walt.credentials",
        "module": "waltid-mdoc-credentials2-jvm",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../waltid-mdoc-credentials2-jvm/1.0.0-SNAPSHOT/waltid-mdoc-credentials2-jvm-1.0.0-SNAPSHOT.module",
        "group": "id.walt.credentials",
        "module": "waltid-mdoc-credentials2-jvm",
        "version": "1.0.0-SNAPSHOT"
      }
    }
  ]
}
