{
  "formatVersion": "1.1",
  "component": {
    "url": "../../waltid-mdoc-credentials/1.0.0-SNAPSHOT/waltid-mdoc-credentials-1.0.0-SNAPSHOT.module",
    "group": "id.walt.mdoc-credentials",
    "module": "waltid-mdoc-credentials",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "waltid-mdoc-credentials-js-1.0.0-SNAPSHOT.klib",
          "url": "waltid-mdoc-credentials-js-1.0.0-SNAPSHOT.klib",
          "size": 411744,
          "sha512": "092e92ce2039b656e7f29f339ff8eb39c864a7c6858552cbe955e2c4fea7ff614bea1533d2e33bb3e255cb2aae2b0aefb530bda878c3f2ad59bb0aceee40d54e",
          "sha256": "049bcb65d23275e01e93e3e755ef3c855d09e18085772d2140c2091d00149aaa",
          "sha1": "d0ffd39b75816c180c2d8a874b21f9a88a3f81f9",
          "md5": "229c2bdb7c8ef18ac59a27daa9d0a561"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.soywiz.korlibs.krypto",
          "module": "krypto",
          "version": {
            "requires": "4.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "waltid-mdoc-credentials-js-1.0.0-SNAPSHOT.klib",
          "url": "waltid-mdoc-credentials-js-1.0.0-SNAPSHOT.klib",
          "size": 411744,
          "sha512": "092e92ce2039b656e7f29f339ff8eb39c864a7c6858552cbe955e2c4fea7ff614bea1533d2e33bb3e255cb2aae2b0aefb530bda878c3f2ad59bb0aceee40d54e",
          "sha256": "049bcb65d23275e01e93e3e755ef3c855d09e18085772d2140c2091d00149aaa",
          "sha1": "d0ffd39b75816c180c2d8a874b21f9a88a3f81f9",
          "md5": "229c2bdb7c8ef18ac59a27daa9d0a561"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "waltid-mdoc-credentials-js-1.0.0-SNAPSHOT-sources.jar",
          "url": "waltid-mdoc-credentials-js-1.0.0-SNAPSHOT-sources.jar",
          "size": 80019,
          "sha512": "3c76ef9ec1933cd488955d495477a3dee14780c178551846625c4b6041329e7882dfa4caf867210c05cb5c949833cba74393eaa55f5b7b03c71881380df1ee88",
          "sha256": "8bcc779c5720a7166117505ecf893ac5901cb35f547181b4a33d6fddedc01501",
          "sha1": "66e233987b657b8a50010b1cce5e8c8c28e6bdda",
          "md5": "c16c11b4730e5525bf2c20757d8308d3"
        }
      ]
    }
  ]
}
