{
  "formatVersion": "1.1",
  "component": {
    "url": "../../waltid-cose/1.0.0-SNAPSHOT/waltid-cose-1.0.0-SNAPSHOT.module",
    "group": "id.walt.crypto",
    "module": "waltid-cose",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "waltid-cose-jvm-1.0.0-SNAPSHOT.jar",
          "url": "waltid-cose-jvm-1.0.0-SNAPSHOT.jar",
          "size": 110288,
          "sha512": "69fbbd882a352e64b398fb46b67264dca0ef598fcbdd0d58d714594e082d2d3a8342377605d1fd0f0f64332e950c2011aeb844f13eb9a2d2201ebad7f2a7be02",
          "sha256": "9dcf34f2c8d256b629f27fcb19186ff3f50c53d9dd9a6ff9d8e7d9f3ced11cab",
          "sha1": "da50c306044ea0ec8edd6ddb65a412b143366770",
          "md5": "44e2ab0ebde98c1cdad9860ca994993b"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.5"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-cbor",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "id.walt.crypto",
          "module": "waltid-crypto",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.kotlincrypto.macs",
          "module": "bom",
          "version": {
            "requires": "0.7.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.kotlincrypto.macs",
          "module": "hmac-sha2"
        }
      ],
      "files": [
        {
          "name": "waltid-cose-jvm-1.0.0-SNAPSHOT.jar",
          "url": "waltid-cose-jvm-1.0.0-SNAPSHOT.jar",
          "size": 110288,
          "sha512": "69fbbd882a352e64b398fb46b67264dca0ef598fcbdd0d58d714594e082d2d3a8342377605d1fd0f0f64332e950c2011aeb844f13eb9a2d2201ebad7f2a7be02",
          "sha256": "9dcf34f2c8d256b629f27fcb19186ff3f50c53d9dd9a6ff9d8e7d9f3ced11cab",
          "sha1": "da50c306044ea0ec8edd6ddb65a412b143366770",
          "md5": "44e2ab0ebde98c1cdad9860ca994993b"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "waltid-cose-jvm-1.0.0-SNAPSHOT-sources.jar",
          "url": "waltid-cose-jvm-1.0.0-SNAPSHOT-sources.jar",
          "size": 11276,
          "sha512": "69fd8740da6dbd418095ddc8f67bdc315ff48bb75630561151613920ae4f5a9209e7a39af207351fd9ee0e6ed7122aa2f03dde4c5719fd10de0f9a6c9a7ed76b",
          "sha256": "1cf2f3de48cce77f7ea04a373873f43a6d9fe1aa325ca21d2732c7a45b87943c",
          "sha1": "8c7efc19dfc8969337b19e8228b1189f10c31d48",
          "md5": "ce5c42c4dce5b486b028e86aef5a7442"
        }
      ]
    }
  ]
}
