{
  "formatVersion": "1.1",
  "component": {
    "url": "../../waltid-openid4vc/1.0.0-SNAPSHOT/waltid-openid4vc-1.0.0-SNAPSHOT.module",
    "group": "id.walt.openid4vc",
    "module": "waltid-openid4vc",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "waltid-openid4vc-jvm-1.0.0-SNAPSHOT.jar",
          "url": "waltid-openid4vc-jvm-1.0.0-SNAPSHOT.jar",
          "size": 847521,
          "sha512": "6e7441892036239dad44fcacf543a55950c9d5dd7c93d37356ae2073e0bb62059f8d8b720b7de85e10d4a704afe604c25359bcca7d23aa37443bc8ebfa1a6062",
          "sha256": "4d280f4c3c6e2c928307b3a2b79950cbe06c0b46972bb9c0367281f9589b45d7",
          "sha1": "57c58896a29e0f79b2d210c8c55b8be7ae8fc707",
          "md5": "5f1a593722ff21c7058c226515570690"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.cose",
          "module": "cose-java",
          "version": {
            "requires": "1.1.1-WALT-SNAPSHOT"
          }
        },
        {
          "group": "com.nimbusds",
          "module": "nimbus-jose-jwt",
          "version": {
            "requires": "10.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.5"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "id.walt.crypto",
          "module": "waltid-crypto",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "id.walt.mdoc-credentials",
          "module": "waltid-mdoc-credentials",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "id.walt.credentials",
          "module": "waltid-w3c-credentials",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "id.walt.policies",
          "module": "waltid-verification-policies",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "id.walt.sdjwt",
          "module": "waltid-sdjwt",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "id.walt.did",
          "module": "waltid-did",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "app.softwork",
          "module": "kotlinx-uuid-core",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.kotlincrypto.hash",
          "module": "bom",
          "version": {
            "requires": "0.6.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.kotlincrypto.hash",
          "module": "sha2"
        }
      ],
      "files": [
        {
          "name": "waltid-openid4vc-jvm-1.0.0-SNAPSHOT.jar",
          "url": "waltid-openid4vc-jvm-1.0.0-SNAPSHOT.jar",
          "size": 847521,
          "sha512": "6e7441892036239dad44fcacf543a55950c9d5dd7c93d37356ae2073e0bb62059f8d8b720b7de85e10d4a704afe604c25359bcca7d23aa37443bc8ebfa1a6062",
          "sha256": "4d280f4c3c6e2c928307b3a2b79950cbe06c0b46972bb9c0367281f9589b45d7",
          "sha1": "57c58896a29e0f79b2d210c8c55b8be7ae8fc707",
          "md5": "5f1a593722ff21c7058c226515570690"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "waltid-openid4vc-jvm-1.0.0-SNAPSHOT-sources.jar",
          "url": "waltid-openid4vc-jvm-1.0.0-SNAPSHOT-sources.jar",
          "size": 101565,
          "sha512": "bb70a69091dba7b3a7b556e8c54238be475796c393946391d7336cdf0f0a5383fe9b867ed6136a150f5d0c813abd3c0468052d2997b673ca7b7f5e40a8844b48",
          "sha256": "d8fd7d3ff71da10724457bd042f52fbfcb9975f75a1e4268c4b5266570784fb6",
          "sha1": "361579935d76bf5e3d0ea963689a80ed21436ee2",
          "md5": "040204977bd87079d2d36010bfbb9ac0"
        }
      ]
    }
  ]
}
