{
  "formatVersion": "1.1",
  "component": {
    "url": "../../waltid-did/1.0.0-SNAPSHOT/waltid-did-1.0.0-SNAPSHOT.module",
    "group": "id.walt.did",
    "module": "waltid-did",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "id.walt.crypto",
          "module": "waltid-crypto",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "love.forte.plugin.suspend-transform",
          "module": "suspend-transform-runtime",
          "version": {
            "requires": "2.2.20-0.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "app.softwork",
          "module": "kotlinx-uuid-core",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "net.thauvin.erik.urlencoder",
          "module": "urlencoder-lib",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.5"
          }
        },
        {
          "group": "love.forte.plugin.suspend-transform",
          "module": "suspend-transform-annotation",
          "version": {
            "requires": "2.2.20-0.13.1"
          }
        }
      ],
      "files": [
        {
          "name": "waltid-did-iosArm64Main-1.0.0-SNAPSHOT.klib",
          "url": "waltid-did-iosarm64-1.0.0-SNAPSHOT.klib",
          "size": 338468,
          "sha512": "71d35486e302e66f827f3c1ce77a00e3a887f0192a237eeaf3ea7eb294cf309912cfcc1533510e92ba739be4c61247e8f737b5965a38255beb80909c463377bc",
          "sha256": "d7f0d8762f8ae0347830c345981204c97a4bfb2c3249494a336e2bf4174a6dd8",
          "sha1": "a7290ace583a1c436627cc63a4d959942514129c",
          "md5": "c5fb442a0b6d2c5c26ad5206a34f822b"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "waltid-did-iosarm64-1.0.0-SNAPSHOT-sources.jar",
          "url": "waltid-did-iosarm64-1.0.0-SNAPSHOT-sources.jar",
          "size": 63372,
          "sha512": "df91dcd36dc58a2b665ba77908d2a9d3190a9e8e6d5e761c86afbf62085b8b4fa1f78562d6dd1dda12fe61d0af98a61676c3c36285c1f8f4ba8d26308e2b1641",
          "sha256": "165266166dafef1aa16c76c47fc68ed273c5a78764863cdc14f7a288c7f75260",
          "sha1": "5baaa9ea94c15d1b12bdefb78d09a13cd8cfa7b6",
          "md5": "95d582ace56f4ba917b2d53ff471c6ab"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "id.walt.crypto",
          "module": "waltid-crypto",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "love.forte.plugin.suspend-transform",
          "module": "suspend-transform-runtime",
          "version": {
            "requires": "2.2.20-0.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-json",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "app.softwork",
          "module": "kotlinx-uuid-core",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "net.thauvin.erik.urlencoder",
          "module": "urlencoder-lib",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging",
          "version": {
            "requires": "7.0.5"
          }
        },
        {
          "group": "love.forte.plugin.suspend-transform",
          "module": "suspend-transform-annotation",
          "version": {
            "requires": "2.2.20-0.13.1"
          }
        }
      ],
      "files": [
        {
          "name": "waltid-did-iosarm64-1.0.0-SNAPSHOT-metadata.jar",
          "url": "waltid-did-iosarm64-1.0.0-SNAPSHOT-metadata.jar",
          "size": 2393,
          "sha512": "8e987f7d22a03c9bd59d6991ed1b3aafd4cb08afb67873da8e9cbbc07d825b576fb48bb660bf7bcde8a392c90364b380b3e422fcf479fbf40ae63de0e1e32440",
          "sha256": "b51cac73c77adef9355207f0389bc9b5577011d99e763b993a7d1afa4f2c51c3",
          "sha1": "aae28692a35c14554dbc317034ddc9e8201bee33",
          "md5": "3cfe947dda78cd7bb66ec57644623c60"
        }
      ]
    }
  ]
}
